// Code generated by protoc-gen-atlas-client. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-client v0.1.0
// - protoc             v5.26.1
// source: api/battle/v1/battle_service.proto

package battlev1opclient

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-sdk-go/api/battle/v1"
	client "github.com/huangyuCN/atlas-sdk-go/client"
)

// BattleService 是 BattleService 的业务 op 客户端 stub（atlas.route.v1 注解生成）：
// 方法直接映射客户端可达 rpc，经会话通道发送；身份由会话携带（消息体不含 token/player_id）。
// 与 gRPC 生成的 BattleServiceClient（连接级 client）不是一回事。
type BattleService struct {
	cli client.Invoker
}

// NewBattleService 以会话内核构造 client stub。
func NewBattleService(cli client.Invoker) *BattleService {
	return &BattleService{cli: cli}
}

// JoinBattle 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *BattleService) JoinBattle(ctx context.Context, req *v1.JoinBattleReq, opts ...client.InvokeOption) (*v1.JoinBattleReply, error) {
	var out v1.JoinBattleReply
	if err := c.cli.Invoke(ctx, `/battle.v1.BattleService/JoinBattle`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// SendFrameInput 单向调用（returns Empty，无回执）。
func (c *BattleService) SendFrameInput(ctx context.Context, req *v1.FrameInputReq, opts ...client.InvokeOption) error {
	return c.cli.Invoke(ctx, `/battle.v1.BattleService/SendFrameInput`, req, nil, opts...)
}

// SyncFrames 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *BattleService) SyncFrames(ctx context.Context, req *v1.SyncFramesReq, opts ...client.InvokeOption) (*v1.SyncFramesReply, error) {
	var out v1.SyncFramesReply
	if err := c.cli.Invoke(ctx, `/battle.v1.BattleService/SyncFrames`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// BattleServiceProtocolOps 是 BattleService 的会话 op 名（按 rpc 名索引）。
var BattleServiceProtocolOps = struct {
	JoinBattle     string
	SendFrameInput string
	SyncFrames     string
}{
	JoinBattle:     "/battle.v1.BattleService/JoinBattle",
	SendFrameInput: "/battle.v1.BattleService/SendFrameInput",
	SyncFrames:     "/battle.v1.BattleService/SyncFrames",
}

// BattleServiceToken 从会话消息里取 Token（无该字段的消息返回零值）。
func BattleServiceToken(msg any) string {
	return ""
}

// BattleServicePlayerID 从会话消息里取 PlayerID（无该字段的消息返回零值）。
func BattleServicePlayerID(msg any) string {
	return ""
}

// BattleServiceExpiresAt 从会话消息里取 ExpiresAt（无该字段的消息返回零值）。
func BattleServiceExpiresAt(msg any) int64 {
	return 0
}

// BattleServicePushOps 是 api/battle/v1/battle_service.proto 声明的服务端推送 op（客户端按 op 分发）。
var BattleServicePushOps = struct {
	FrameBroadcast  string
	BattleEndNotify string
}{
	FrameBroadcast:  "/battle.v1.FrameBroadcast",
	BattleEndNotify: "/battle.v1.BattleEndNotify",
}
