// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/atlas/v1/route.proto

package atlasroutepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Access int32

const (
	Access_ACCESS_UNSPECIFIED Access = 0
	Access_ACCESS_CLIENT      Access = 1
	Access_ACCESS_INTERNAL    Access = 2
)

// Enum value maps for Access.
var (
	Access_name = map[int32]string{
		0: "ACCESS_UNSPECIFIED",
		1: "ACCESS_CLIENT",
		2: "ACCESS_INTERNAL",
	}
	Access_value = map[string]int32{
		"ACCESS_UNSPECIFIED": 0,
		"ACCESS_CLIENT":      1,
		"ACCESS_INTERNAL":    2,
	}
)

func (x Access) Enum() *Access {
	p := new(Access)
	*p = x
	return p
}

func (x Access) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Access) Descriptor() protoreflect.EnumDescriptor {
	return file_api_atlas_v1_route_proto_enumTypes[0].Descriptor()
}

func (Access) Type() protoreflect.EnumType {
	return &file_api_atlas_v1_route_proto_enumTypes[0]
}

func (x Access) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Access.Descriptor instead.
func (Access) EnumDescriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{0}
}

type UidSource int32

const (
	UidSource_UID_SOURCE_UNSPECIFIED UidSource = 0
	UidSource_UID_SOURCE_SESSION     UidSource = 1
	UidSource_UID_SOURCE_FIELD       UidSource = 2
)

// Enum value maps for UidSource.
var (
	UidSource_name = map[int32]string{
		0: "UID_SOURCE_UNSPECIFIED",
		1: "UID_SOURCE_SESSION",
		2: "UID_SOURCE_FIELD",
	}
	UidSource_value = map[string]int32{
		"UID_SOURCE_UNSPECIFIED": 0,
		"UID_SOURCE_SESSION":     1,
		"UID_SOURCE_FIELD":       2,
	}
)

func (x UidSource) Enum() *UidSource {
	p := new(UidSource)
	*p = x
	return p
}

func (x UidSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UidSource) Descriptor() protoreflect.EnumDescriptor {
	return file_api_atlas_v1_route_proto_enumTypes[1].Descriptor()
}

func (UidSource) Type() protoreflect.EnumType {
	return &file_api_atlas_v1_route_proto_enumTypes[1]
}

func (x UidSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UidSource.Descriptor instead.
func (UidSource) EnumDescriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{1}
}

type Idempotency int32

const (
	Idempotency_IDEMPOTENCY_UNSPECIFIED Idempotency = 0
	Idempotency_IDEMPOTENT              Idempotency = 1
)

// Enum value maps for Idempotency.
var (
	Idempotency_name = map[int32]string{
		0: "IDEMPOTENCY_UNSPECIFIED",
		1: "IDEMPOTENT",
	}
	Idempotency_value = map[string]int32{
		"IDEMPOTENCY_UNSPECIFIED": 0,
		"IDEMPOTENT":              1,
	}
)

func (x Idempotency) Enum() *Idempotency {
	p := new(Idempotency)
	*p = x
	return p
}

func (x Idempotency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Idempotency) Descriptor() protoreflect.EnumDescriptor {
	return file_api_atlas_v1_route_proto_enumTypes[2].Descriptor()
}

func (Idempotency) Type() protoreflect.EnumType {
	return &file_api_atlas_v1_route_proto_enumTypes[2]
}

func (x Idempotency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Idempotency.Descriptor instead.
func (Idempotency) EnumDescriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{2}
}

type RateLimitScope int32

const (
	RateLimitScope_RATE_LIMIT_SCOPE_UNSPECIFIED RateLimitScope = 0
	RateLimitScope_RATE_LIMIT_SCOPE_PLAYER      RateLimitScope = 1
	RateLimitScope_RATE_LIMIT_SCOPE_GLOBAL      RateLimitScope = 2
)

// Enum value maps for RateLimitScope.
var (
	RateLimitScope_name = map[int32]string{
		0: "RATE_LIMIT_SCOPE_UNSPECIFIED",
		1: "RATE_LIMIT_SCOPE_PLAYER",
		2: "RATE_LIMIT_SCOPE_GLOBAL",
	}
	RateLimitScope_value = map[string]int32{
		"RATE_LIMIT_SCOPE_UNSPECIFIED": 0,
		"RATE_LIMIT_SCOPE_PLAYER":      1,
		"RATE_LIMIT_SCOPE_GLOBAL":      2,
	}
)

func (x RateLimitScope) Enum() *RateLimitScope {
	p := new(RateLimitScope)
	*p = x
	return p
}

func (x RateLimitScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitScope) Descriptor() protoreflect.EnumDescriptor {
	return file_api_atlas_v1_route_proto_enumTypes[3].Descriptor()
}

func (RateLimitScope) Type() protoreflect.EnumType {
	return &file_api_atlas_v1_route_proto_enumTypes[3]
}

func (x RateLimitScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitScope.Descriptor instead.
func (RateLimitScope) EnumDescriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{3}
}

type RouteRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Access        Access                 `protobuf:"varint,2,opt,name=access,proto3,enum=atlas.route.v1.Access" json:"access,omitempty"`
	Uid           UidSource              `protobuf:"varint,3,opt,name=uid,proto3,enum=atlas.route.v1.UidSource" json:"uid,omitempty"`
	UidField      string                 `protobuf:"bytes,4,opt,name=uid_field,json=uidField,proto3" json:"uid_field,omitempty"`
	Idempotency   Idempotency            `protobuf:"varint,5,opt,name=idempotency,proto3,enum=atlas.route.v1.Idempotency" json:"idempotency,omitempty"`
	Since         string                 `protobuf:"bytes,6,opt,name=since,proto3" json:"since,omitempty"`
	Deprecated    string                 `protobuf:"bytes,7,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	Replacement   string                 `protobuf:"bytes,8,opt,name=replacement,proto3" json:"replacement,omitempty"`
	RateLimit     *RateLimit             `protobuf:"bytes,9,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRule) Reset() {
	*x = RouteRule{}
	mi := &file_api_atlas_v1_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRule) ProtoMessage() {}

func (x *RouteRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_atlas_v1_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRule.ProtoReflect.Descriptor instead.
func (*RouteRule) Descriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRule) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *RouteRule) GetAccess() Access {
	if x != nil {
		return x.Access
	}
	return Access_ACCESS_UNSPECIFIED
}

func (x *RouteRule) GetUid() UidSource {
	if x != nil {
		return x.Uid
	}
	return UidSource_UID_SOURCE_UNSPECIFIED
}

func (x *RouteRule) GetUidField() string {
	if x != nil {
		return x.UidField
	}
	return ""
}

func (x *RouteRule) GetIdempotency() Idempotency {
	if x != nil {
		return x.Idempotency
	}
	return Idempotency_IDEMPOTENCY_UNSPECIFIED
}

func (x *RouteRule) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *RouteRule) GetDeprecated() string {
	if x != nil {
		return x.Deprecated
	}
	return ""
}

func (x *RouteRule) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *RouteRule) GetRateLimit() *RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type RouteOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        Access                 `protobuf:"varint,1,opt,name=access,proto3,enum=atlas.route.v1.Access" json:"access,omitempty"`
	Uid           UidSource              `protobuf:"varint,2,opt,name=uid,proto3,enum=atlas.route.v1.UidSource" json:"uid,omitempty"`
	UidField      string                 `protobuf:"bytes,3,opt,name=uid_field,json=uidField,proto3" json:"uid_field,omitempty"`
	Idempotency   Idempotency            `protobuf:"varint,4,opt,name=idempotency,proto3,enum=atlas.route.v1.Idempotency" json:"idempotency,omitempty"`
	Since         string                 `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	Deprecated    string                 `protobuf:"bytes,6,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	Replacement   string                 `protobuf:"bytes,7,opt,name=replacement,proto3" json:"replacement,omitempty"`
	RateLimit     *RateLimit             `protobuf:"bytes,8,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteOverride) Reset() {
	*x = RouteOverride{}
	mi := &file_api_atlas_v1_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOverride) ProtoMessage() {}

func (x *RouteOverride) ProtoReflect() protoreflect.Message {
	mi := &file_api_atlas_v1_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOverride.ProtoReflect.Descriptor instead.
func (*RouteOverride) Descriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{1}
}

func (x *RouteOverride) GetAccess() Access {
	if x != nil {
		return x.Access
	}
	return Access_ACCESS_UNSPECIFIED
}

func (x *RouteOverride) GetUid() UidSource {
	if x != nil {
		return x.Uid
	}
	return UidSource_UID_SOURCE_UNSPECIFIED
}

func (x *RouteOverride) GetUidField() string {
	if x != nil {
		return x.UidField
	}
	return ""
}

func (x *RouteOverride) GetIdempotency() Idempotency {
	if x != nil {
		return x.Idempotency
	}
	return Idempotency_IDEMPOTENCY_UNSPECIFIED
}

func (x *RouteOverride) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *RouteOverride) GetDeprecated() string {
	if x != nil {
		return x.Deprecated
	}
	return ""
}

func (x *RouteOverride) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *RouteOverride) GetRateLimit() *RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qps           uint32                 `protobuf:"varint,1,opt,name=qps,proto3" json:"qps,omitempty"`
	Burst         uint32                 `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	Scope         RateLimitScope         `protobuf:"varint,3,opt,name=scope,proto3,enum=atlas.route.v1.RateLimitScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_api_atlas_v1_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_api_atlas_v1_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_api_atlas_v1_route_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimit) GetQps() uint32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *RateLimit) GetBurst() uint32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimit) GetScope() RateLimitScope {
	if x != nil {
		return x.Scope
	}
	return RateLimitScope_RATE_LIMIT_SCOPE_UNSPECIFIED
}

var file_api_atlas_v1_route_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*RouteRule)(nil),
		Field:         71001,
		Name:          "atlas.route.v1.service_route",
		Tag:           "bytes,71001,opt,name=service_route",
		Filename:      "api/atlas/v1/route.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RouteOverride)(nil),
		Field:         71002,
		Name:          "atlas.route.v1.rpc_route",
		Tag:           "bytes,71002,opt,name=rpc_route",
		Filename:      "api/atlas/v1/route.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         71003,
		Name:          "atlas.route.v1.push",
		Tag:           "varint,71003,opt,name=push",
		Filename:      "api/atlas/v1/route.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional atlas.route.v1.RouteRule service_route = 71001;
	E_ServiceRoute = &file_api_atlas_v1_route_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional atlas.route.v1.RouteOverride rpc_route = 71002;
	E_RpcRoute = &file_api_atlas_v1_route_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool push = 71003;
	E_Push = &file_api_atlas_v1_route_proto_extTypes[2]
)

var File_api_atlas_v1_route_proto protoreflect.FileDescriptor

const file_api_atlas_v1_route_proto_rawDesc = "" +
	"\n" +
	"\x18api/atlas/v1/route.proto\x12\x0eatlas.route.v1\x1a google/protobuf/descriptor.proto\"\xec\x02\n" +
	"\tRouteRule\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12.\n" +
	"\x06access\x18\x02 \x01(\x0e2\x16.atlas.route.v1.AccessR\x06access\x12+\n" +
	"\x03uid\x18\x03 \x01(\x0e2\x19.atlas.route.v1.UidSourceR\x03uid\x12\x1b\n" +
	"\tuid_field\x18\x04 \x01(\tR\buidField\x12=\n" +
	"\vidempotency\x18\x05 \x01(\x0e2\x1b.atlas.route.v1.IdempotencyR\vidempotency\x12\x14\n" +
	"\x05since\x18\x06 \x01(\tR\x05since\x12\x1e\n" +
	"\n" +
	"deprecated\x18\a \x01(\tR\n" +
	"deprecated\x12 \n" +
	"\vreplacement\x18\b \x01(\tR\vreplacement\x128\n" +
	"\n" +
	"rate_limit\x18\t \x01(\v2\x19.atlas.route.v1.RateLimitR\trateLimit\"\xda\x02\n" +
	"\rRouteOverride\x12.\n" +
	"\x06access\x18\x01 \x01(\x0e2\x16.atlas.route.v1.AccessR\x06access\x12+\n" +
	"\x03uid\x18\x02 \x01(\x0e2\x19.atlas.route.v1.UidSourceR\x03uid\x12\x1b\n" +
	"\tuid_field\x18\x03 \x01(\tR\buidField\x12=\n" +
	"\vidempotency\x18\x04 \x01(\x0e2\x1b.atlas.route.v1.IdempotencyR\vidempotency\x12\x14\n" +
	"\x05since\x18\x05 \x01(\tR\x05since\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x06 \x01(\tR\n" +
	"deprecated\x12 \n" +
	"\vreplacement\x18\a \x01(\tR\vreplacement\x128\n" +
	"\n" +
	"rate_limit\x18\b \x01(\v2\x19.atlas.route.v1.RateLimitR\trateLimit\"i\n" +
	"\tRateLimit\x12\x10\n" +
	"\x03qps\x18\x01 \x01(\rR\x03qps\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\rR\x05burst\x124\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x1e.atlas.route.v1.RateLimitScopeR\x05scope*H\n" +
	"\x06Access\x12\x16\n" +
	"\x12ACCESS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACCESS_CLIENT\x10\x01\x12\x13\n" +
	"\x0fACCESS_INTERNAL\x10\x02*U\n" +
	"\tUidSource\x12\x1a\n" +
	"\x16UID_SOURCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12UID_SOURCE_SESSION\x10\x01\x12\x14\n" +
	"\x10UID_SOURCE_FIELD\x10\x02*:\n" +
	"\vIdempotency\x12\x1b\n" +
	"\x17IDEMPOTENCY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"IDEMPOTENT\x10\x01*l\n" +
	"\x0eRateLimitScope\x12 \n" +
	"\x1cRATE_LIMIT_SCOPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RATE_LIMIT_SCOPE_PLAYER\x10\x01\x12\x1b\n" +
	"\x17RATE_LIMIT_SCOPE_GLOBAL\x10\x02:a\n" +
	"\rservice_route\x12\x1f.google.protobuf.ServiceOptions\x18٪\x04 \x01(\v2\x19.atlas.route.v1.RouteRuleR\fserviceRoute:\\\n" +
	"\trpc_route\x12\x1e.google.protobuf.MethodOptions\x18ڪ\x04 \x01(\v2\x1d.atlas.route.v1.RouteOverrideR\brpcRoute:5\n" +
	"\x04push\x12\x1f.google.protobuf.MessageOptions\x18۪\x04 \x01(\bR\x04pushB6Z4github.com/huangyuCN/atlas/api/atlas/v1;atlasroutepbb\x06proto3"

var (
	file_api_atlas_v1_route_proto_rawDescOnce sync.Once
	file_api_atlas_v1_route_proto_rawDescData []byte
)

func file_api_atlas_v1_route_proto_rawDescGZIP() []byte {
	file_api_atlas_v1_route_proto_rawDescOnce.Do(func() {
		file_api_atlas_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_atlas_v1_route_proto_rawDesc), len(file_api_atlas_v1_route_proto_rawDesc)))
	})
	return file_api_atlas_v1_route_proto_rawDescData
}

var file_api_atlas_v1_route_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_atlas_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_atlas_v1_route_proto_goTypes = []any{
	(Access)(0),                         // 0: atlas.route.v1.Access
	(UidSource)(0),                      // 1: atlas.route.v1.UidSource
	(Idempotency)(0),                    // 2: atlas.route.v1.Idempotency
	(RateLimitScope)(0),                 // 3: atlas.route.v1.RateLimitScope
	(*RouteRule)(nil),                   // 4: atlas.route.v1.RouteRule
	(*RouteOverride)(nil),               // 5: atlas.route.v1.RouteOverride
	(*RateLimit)(nil),                   // 6: atlas.route.v1.RateLimit
	(*descriptorpb.ServiceOptions)(nil), // 7: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 8: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
}
var file_api_atlas_v1_route_proto_depIdxs = []int32{
	0,  // 0: atlas.route.v1.RouteRule.access:type_name -> atlas.route.v1.Access
	1,  // 1: atlas.route.v1.RouteRule.uid:type_name -> atlas.route.v1.UidSource
	2,  // 2: atlas.route.v1.RouteRule.idempotency:type_name -> atlas.route.v1.Idempotency
	6,  // 3: atlas.route.v1.RouteRule.rate_limit:type_name -> atlas.route.v1.RateLimit
	0,  // 4: atlas.route.v1.RouteOverride.access:type_name -> atlas.route.v1.Access
	1,  // 5: atlas.route.v1.RouteOverride.uid:type_name -> atlas.route.v1.UidSource
	2,  // 6: atlas.route.v1.RouteOverride.idempotency:type_name -> atlas.route.v1.Idempotency
	6,  // 7: atlas.route.v1.RouteOverride.rate_limit:type_name -> atlas.route.v1.RateLimit
	3,  // 8: atlas.route.v1.RateLimit.scope:type_name -> atlas.route.v1.RateLimitScope
	7,  // 9: atlas.route.v1.service_route:extendee -> google.protobuf.ServiceOptions
	8,  // 10: atlas.route.v1.rpc_route:extendee -> google.protobuf.MethodOptions
	9,  // 11: atlas.route.v1.push:extendee -> google.protobuf.MessageOptions
	4,  // 12: atlas.route.v1.service_route:type_name -> atlas.route.v1.RouteRule
	5,  // 13: atlas.route.v1.rpc_route:type_name -> atlas.route.v1.RouteOverride
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	12, // [12:14] is the sub-list for extension type_name
	9,  // [9:12] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_atlas_v1_route_proto_init() }
func file_api_atlas_v1_route_proto_init() {
	if File_api_atlas_v1_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_atlas_v1_route_proto_rawDesc), len(file_api_atlas_v1_route_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_api_atlas_v1_route_proto_goTypes,
		DependencyIndexes: file_api_atlas_v1_route_proto_depIdxs,
		EnumInfos:         file_api_atlas_v1_route_proto_enumTypes,
		MessageInfos:      file_api_atlas_v1_route_proto_msgTypes,
		ExtensionInfos:    file_api_atlas_v1_route_proto_extTypes,
	}.Build()
	File_api_atlas_v1_route_proto = out.File
	file_api_atlas_v1_route_proto_goTypes = nil
	file_api_atlas_v1_route_proto_depIdxs = nil
}
