// gatewayv1 是 SDK 真机冒烟用的最小 gateway 认证协议子集（字段与
// atlas-game-layout api/gateway/v1/auth.proto 对齐；去掉跨包 PlayerSummary
// 引用——LoginReply 仅取 player_id/token，服务端多余字段由解码端忽略）。
// 仅测试用途：真机三编码（json/protojson/protobuf）验证 service op 形态。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: gatewayv1/auth.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gatewayv1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_gatewayv1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gatewayv1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_gatewayv1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_gatewayv1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *HeartbeatRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type HeartbeatReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ts               int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	ServerTimeUnixMs uint64                 `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_gatewayv1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatReply) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *HeartbeatReply) GetServerTimeUnixMs() uint64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

// JoinBattle 战斗绑定（UDP/KCP 战斗通道 op；模板 D6 战斗协议）。
type JoinBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BattleId      string                 `protobuf:"bytes,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleRequest) Reset() {
	*x = JoinBattleRequest{}
	mi := &file_gatewayv1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleRequest) ProtoMessage() {}

func (x *JoinBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleRequest.ProtoReflect.Descriptor instead.
func (*JoinBattleRequest) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *JoinBattleRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinBattleRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type JoinBattleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleReply) Reset() {
	*x = JoinBattleReply{}
	mi := &file_gatewayv1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleReply) ProtoMessage() {}

func (x *JoinBattleReply) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayv1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleReply.ProtoReflect.Descriptor instead.
func (*JoinBattleReply) Descriptor() ([]byte, []int) {
	return file_gatewayv1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *JoinBattleReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinBattleReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gatewayv1_auth_proto protoreflect.FileDescriptor

const file_gatewayv1_auth_proto_rawDesc = "" +
	"\n" +
	"\x14gatewayv1/auth.proto\x12\n" +
	"gateway.v1\"c\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\",\n" +
	"\rRegisterReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"G\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"?\n" +
	"\n" +
	"LoginReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"U\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"O\n" +
	"\x0eHeartbeatReply\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12-\n" +
	"\x13server_time_unix_ms\x18\x02 \x01(\x04R\x10serverTimeUnixMs\"c\n" +
	"\x11JoinBattleRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\tR\bbattleId\";\n" +
	"\x0fJoinBattleReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd3\x01\n" +
	"\vGatewayAuth\x12B\n" +
	"\bRegister\x12\x1b.gateway.v1.RegisterRequest\x1a\x19.gateway.v1.RegisterReply\x129\n" +
	"\x05Login\x12\x18.gateway.v1.LoginRequest\x1a\x16.gateway.v1.LoginReply\x12E\n" +
	"\tHeartbeat\x12\x1c.gateway.v1.HeartbeatRequest\x1a\x1a.gateway.v1.HeartbeatReplyBFZDgithub.com/huangyuCN/atlas-sdk-go/examples/smoke/gatewayv1;gatewayv1b\x06proto3"

var (
	file_gatewayv1_auth_proto_rawDescOnce sync.Once
	file_gatewayv1_auth_proto_rawDescData []byte
)

func file_gatewayv1_auth_proto_rawDescGZIP() []byte {
	file_gatewayv1_auth_proto_rawDescOnce.Do(func() {
		file_gatewayv1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gatewayv1_auth_proto_rawDesc), len(file_gatewayv1_auth_proto_rawDesc)))
	})
	return file_gatewayv1_auth_proto_rawDescData
}

var file_gatewayv1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gatewayv1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: gateway.v1.RegisterRequest
	(*RegisterReply)(nil),     // 1: gateway.v1.RegisterReply
	(*LoginRequest)(nil),      // 2: gateway.v1.LoginRequest
	(*LoginReply)(nil),        // 3: gateway.v1.LoginReply
	(*HeartbeatRequest)(nil),  // 4: gateway.v1.HeartbeatRequest
	(*HeartbeatReply)(nil),    // 5: gateway.v1.HeartbeatReply
	(*JoinBattleRequest)(nil), // 6: gateway.v1.JoinBattleRequest
	(*JoinBattleReply)(nil),   // 7: gateway.v1.JoinBattleReply
}
var file_gatewayv1_auth_proto_depIdxs = []int32{
	0, // 0: gateway.v1.GatewayAuth.Register:input_type -> gateway.v1.RegisterRequest
	2, // 1: gateway.v1.GatewayAuth.Login:input_type -> gateway.v1.LoginRequest
	4, // 2: gateway.v1.GatewayAuth.Heartbeat:input_type -> gateway.v1.HeartbeatRequest
	1, // 3: gateway.v1.GatewayAuth.Register:output_type -> gateway.v1.RegisterReply
	3, // 4: gateway.v1.GatewayAuth.Login:output_type -> gateway.v1.LoginReply
	5, // 5: gateway.v1.GatewayAuth.Heartbeat:output_type -> gateway.v1.HeartbeatReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gatewayv1_auth_proto_init() }
func file_gatewayv1_auth_proto_init() {
	if File_gatewayv1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gatewayv1_auth_proto_rawDesc), len(file_gatewayv1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gatewayv1_auth_proto_goTypes,
		DependencyIndexes: file_gatewayv1_auth_proto_depIdxs,
		MessageInfos:      file_gatewayv1_auth_proto_msgTypes,
	}.Build()
	File_gatewayv1_auth_proto = out.File
	file_gatewayv1_auth_proto_goTypes = nil
	file_gatewayv1_auth_proto_depIdxs = nil
}
