// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/gateway/v1/session.proto

package gatewayv1

import (
	_ "github.com/huangyuCN/atlas-sdk-go/api/atlas/v1"
	v1 "github.com/huangyuCN/atlas-sdk-go/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickedReason int32

const (
	KickedReason_KICKED_REASON_UNSPECIFIED         KickedReason = 0
	KickedReason_KICKED_REASON_LOGGED_IN_ELSEWHERE KickedReason = 1
	KickedReason_KICKED_REASON_SESSION_EXPIRED     KickedReason = 2
)

// Enum value maps for KickedReason.
var (
	KickedReason_name = map[int32]string{
		0: "KICKED_REASON_UNSPECIFIED",
		1: "KICKED_REASON_LOGGED_IN_ELSEWHERE",
		2: "KICKED_REASON_SESSION_EXPIRED",
	}
	KickedReason_value = map[string]int32{
		"KICKED_REASON_UNSPECIFIED":         0,
		"KICKED_REASON_LOGGED_IN_ELSEWHERE": 1,
		"KICKED_REASON_SESSION_EXPIRED":     2,
	}
)

func (x KickedReason) Enum() *KickedReason {
	p := new(KickedReason)
	*p = x
	return p
}

func (x KickedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KickedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gateway_v1_session_proto_enumTypes[0].Descriptor()
}

func (KickedReason) Type() protoreflect.EnumType {
	return &file_api_gateway_v1_session_proto_enumTypes[0]
}

func (x KickedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KickedReason.Descriptor instead.
func (KickedReason) EnumDescriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientEnd     string                 `protobuf:"bytes,4,opt,name=client_end,json=clientEnd,proto3" json:"client_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *LoginRequest) GetClientEnd() string {
	if x != nil {
		return x.ClientEnd
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientEnd     string                 `protobuf:"bytes,4,opt,name=client_end,json=clientEnd,proto3" json:"client_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResumeRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ResumeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ResumeRequest) GetClientEnd() string {
	if x != nil {
		return x.ClientEnd
	}
	return ""
}

type ResumeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeReply) Reset() {
	*x = ResumeReply{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeReply) ProtoMessage() {}

func (x *ResumeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeReply.ProtoReflect.Descriptor instead.
func (*ResumeReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type HeartbeatReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeUnixMs uint64                 `protobuf:"varint,1,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatReply) GetServerTimeUnixMs() uint64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{8}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{9}
}

type KickedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        KickedReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=gateway.v1.KickedReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickedNotify) Reset() {
	*x = KickedNotify{}
	mi := &file_api_gateway_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickedNotify) ProtoMessage() {}

func (x *KickedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickedNotify.ProtoReflect.Descriptor instead.
func (*KickedNotify) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *KickedNotify) GetReason() KickedReason {
	if x != nil {
		return x.Reason
	}
	return KickedReason_KICKED_REASON_UNSPECIFIED
}

var File_api_gateway_v1_session_proto protoreflect.FileDescriptor

const file_api_gateway_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1capi/gateway/v1/session.proto\x12\n" +
	"gateway.v1\x1a\x18api/atlas/v1/route.proto\x1a\x1aapi/common/v1/common.proto\"c\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\",\n" +
	"\rRegisterReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x8d\x01\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12\x1d\n" +
	"\n" +
	"client_end\x18\x04 \x01(\tR\tclientEnd\"q\n" +
	"\n" +
	"LoginReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x120\n" +
	"\x06player\x18\x03 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"\x88\x01\n" +
	"\rResumeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12\x1d\n" +
	"\n" +
	"client_end\x18\x04 \x01(\tR\tclientEnd\"*\n" +
	"\vResumeReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\"\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\"?\n" +
	"\x0eHeartbeatReply\x12-\n" +
	"\x13server_time_unix_ms\x18\x01 \x01(\x04R\x10serverTimeUnixMs\"\x0f\n" +
	"\rLogoutRequest\"\r\n" +
	"\vLogoutReply\"F\n" +
	"\fKickedNotify\x120\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x18.gateway.v1.KickedReasonR\x06reason:\x04\xd8\xd5\"\x01*w\n" +
	"\fKickedReason\x12\x1d\n" +
	"\x19KICKED_REASON_UNSPECIFIED\x10\x00\x12%\n" +
	"!KICKED_REASON_LOGGED_IN_ELSEWHERE\x10\x01\x12!\n" +
	"\x1dKICKED_REASON_SESSION_EXPIRED\x10\x022\xd3\x02\n" +
	"\aSession\x12B\n" +
	"\bRegister\x12\x1b.gateway.v1.RegisterRequest\x1a\x19.gateway.v1.RegisterReply\x129\n" +
	"\x05Login\x12\x18.gateway.v1.LoginRequest\x1a\x16.gateway.v1.LoginReply\x12<\n" +
	"\x06Resume\x12\x19.gateway.v1.ResumeRequest\x1a\x17.gateway.v1.ResumeReply\x12<\n" +
	"\x06Logout\x12\x19.gateway.v1.LogoutRequest\x1a\x17.gateway.v1.LogoutReply\x12E\n" +
	"\tHeartbeat\x12\x1c.gateway.v1.HeartbeatRequest\x1a\x1a.gateway.v1.HeartbeatReply\x1a\x06\xca\xd5\"\x02\x10\x01BAZ?github.com/huangyuCN/atlas-game-layout/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_session_proto_rawDescOnce sync.Once
	file_api_gateway_v1_session_proto_rawDescData []byte
)

func file_api_gateway_v1_session_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_session_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_session_proto_rawDesc), len(file_api_gateway_v1_session_proto_rawDesc)))
	})
	return file_api_gateway_v1_session_proto_rawDescData
}

var file_api_gateway_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gateway_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_gateway_v1_session_proto_goTypes = []any{
	(KickedReason)(0),        // 0: gateway.v1.KickedReason
	(*RegisterRequest)(nil),  // 1: gateway.v1.RegisterRequest
	(*RegisterReply)(nil),    // 2: gateway.v1.RegisterReply
	(*LoginRequest)(nil),     // 3: gateway.v1.LoginRequest
	(*LoginReply)(nil),       // 4: gateway.v1.LoginReply
	(*ResumeRequest)(nil),    // 5: gateway.v1.ResumeRequest
	(*ResumeReply)(nil),      // 6: gateway.v1.ResumeReply
	(*HeartbeatRequest)(nil), // 7: gateway.v1.HeartbeatRequest
	(*HeartbeatReply)(nil),   // 8: gateway.v1.HeartbeatReply
	(*LogoutRequest)(nil),    // 9: gateway.v1.LogoutRequest
	(*LogoutReply)(nil),      // 10: gateway.v1.LogoutReply
	(*KickedNotify)(nil),     // 11: gateway.v1.KickedNotify
	(*v1.PlayerSummary)(nil), // 12: common.v1.PlayerSummary
}
var file_api_gateway_v1_session_proto_depIdxs = []int32{
	12, // 0: gateway.v1.LoginReply.player:type_name -> common.v1.PlayerSummary
	0,  // 1: gateway.v1.KickedNotify.reason:type_name -> gateway.v1.KickedReason
	1,  // 2: gateway.v1.Session.Register:input_type -> gateway.v1.RegisterRequest
	3,  // 3: gateway.v1.Session.Login:input_type -> gateway.v1.LoginRequest
	5,  // 4: gateway.v1.Session.Resume:input_type -> gateway.v1.ResumeRequest
	9,  // 5: gateway.v1.Session.Logout:input_type -> gateway.v1.LogoutRequest
	7,  // 6: gateway.v1.Session.Heartbeat:input_type -> gateway.v1.HeartbeatRequest
	2,  // 7: gateway.v1.Session.Register:output_type -> gateway.v1.RegisterReply
	4,  // 8: gateway.v1.Session.Login:output_type -> gateway.v1.LoginReply
	6,  // 9: gateway.v1.Session.Resume:output_type -> gateway.v1.ResumeReply
	10, // 10: gateway.v1.Session.Logout:output_type -> gateway.v1.LogoutReply
	8,  // 11: gateway.v1.Session.Heartbeat:output_type -> gateway.v1.HeartbeatReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_session_proto_init() }
func file_api_gateway_v1_session_proto_init() {
	if File_api_gateway_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_session_proto_rawDesc), len(file_api_gateway_v1_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_session_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_session_proto_depIdxs,
		EnumInfos:         file_api_gateway_v1_session_proto_enumTypes,
		MessageInfos:      file_api_gateway_v1_session_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_session_proto = out.File
	file_api_gateway_v1_session_proto_goTypes = nil
	file_api_gateway_v1_session_proto_depIdxs = nil
}
