// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/battle/v1/battle.proto

package battlev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	BattleId      string                 `protobuf:"bytes,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBattleRequest) Reset() {
	*x = CreateBattleRequest{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleRequest) ProtoMessage() {}

func (x *CreateBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleRequest.ProtoReflect.Descriptor instead.
func (*CreateBattleRequest) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBattleRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CreateBattleRequest) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *CreateBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type CreateBattleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBattleReply) Reset() {
	*x = CreateBattleReply{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBattleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBattleReply) ProtoMessage() {}

func (x *CreateBattleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBattleReply.ProtoReflect.Descriptor instead.
func (*CreateBattleReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBattleReply) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type GetBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleRequest) Reset() {
	*x = GetBattleRequest{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleRequest) ProtoMessage() {}

func (x *GetBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleRequest.ProtoReflect.Descriptor instead.
func (*GetBattleRequest) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{2}
}

func (x *GetBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type GetBattleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBattleReply) Reset() {
	*x = GetBattleReply{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBattleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattleReply) ProtoMessage() {}

func (x *GetBattleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattleReply.ProtoReflect.Descriptor instead.
func (*GetBattleReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{3}
}

func (x *GetBattleReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type PlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Win           bool                   `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResult) Reset() {
	*x = PlayerResult{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResult) ProtoMessage() {}

func (x *PlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResult.ProtoReflect.Descriptor instead.
func (*PlayerResult) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerResult) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerResult) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *PlayerResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type BattleSettledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Players       []*PlayerResult        `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleSettledEvent) Reset() {
	*x = BattleSettledEvent{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleSettledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleSettledEvent) ProtoMessage() {}

func (x *BattleSettledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleSettledEvent.ProtoReflect.Descriptor instead.
func (*BattleSettledEvent) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{5}
}

func (x *BattleSettledEvent) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleSettledEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *BattleSettledEvent) GetPlayers() []*PlayerResult {
	if x != nil {
		return x.Players
	}
	return nil
}

type GetStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateReq) Reset() {
	*x = GetStateReq{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReq) ProtoMessage() {}

func (x *GetStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReq.ProtoReflect.Descriptor instead.
func (*GetStateReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{6}
}

func (x *GetStateReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type GetStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CurrentFrame  uint64                 `protobuf:"varint,2,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
	PlayerCount   uint32                 `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateReply) Reset() {
	*x = GetStateReply{}
	mi := &file_api_battle_v1_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateReply) ProtoMessage() {}

func (x *GetStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateReply.ProtoReflect.Descriptor instead.
func (*GetStateReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_proto_rawDescGZIP(), []int{7}
}

func (x *GetStateReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStateReply) GetCurrentFrame() uint64 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

func (x *GetStateReply) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

var File_api_battle_v1_battle_proto protoreflect.FileDescriptor

const file_api_battle_v1_battle_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/battle/v1/battle.proto\x12\tbattle.v1\"l\n" +
	"\x13CreateBattleRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\tR\bbattleId\"0\n" +
	"\x11CreateBattleReply\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"/\n" +
	"\x10GetBattleRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"&\n" +
	"\x0eGetBattleReply\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"S\n" +
	"\fPlayerResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x10\n" +
	"\x03win\x18\x02 \x01(\bR\x03win\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"\x7f\n" +
	"\x12BattleSettledEvent\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x19\n" +
	"\bmatch_id\x18\x02 \x01(\tR\amatchId\x121\n" +
	"\aplayers\x18\x03 \x03(\v2\x17.battle.v1.PlayerResultR\aplayers\"*\n" +
	"\vGetStateReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"m\n" +
	"\rGetStateReply\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12#\n" +
	"\rcurrent_frame\x18\x02 \x01(\x04R\fcurrentFrame\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\rR\vplayerCountB?Z=github.com/huangyuCN/atlas-game-layout/api/battle/v1;battlev1b\x06proto3"

var (
	file_api_battle_v1_battle_proto_rawDescOnce sync.Once
	file_api_battle_v1_battle_proto_rawDescData []byte
)

func file_api_battle_v1_battle_proto_rawDescGZIP() []byte {
	file_api_battle_v1_battle_proto_rawDescOnce.Do(func() {
		file_api_battle_v1_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_battle_v1_battle_proto_rawDesc), len(file_api_battle_v1_battle_proto_rawDesc)))
	})
	return file_api_battle_v1_battle_proto_rawDescData
}

var file_api_battle_v1_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_battle_v1_battle_proto_goTypes = []any{
	(*CreateBattleRequest)(nil), // 0: battle.v1.CreateBattleRequest
	(*CreateBattleReply)(nil),   // 1: battle.v1.CreateBattleReply
	(*GetBattleRequest)(nil),    // 2: battle.v1.GetBattleRequest
	(*GetBattleReply)(nil),      // 3: battle.v1.GetBattleReply
	(*PlayerResult)(nil),        // 4: battle.v1.PlayerResult
	(*BattleSettledEvent)(nil),  // 5: battle.v1.BattleSettledEvent
	(*GetStateReq)(nil),         // 6: battle.v1.GetStateReq
	(*GetStateReply)(nil),       // 7: battle.v1.GetStateReply
}
var file_api_battle_v1_battle_proto_depIdxs = []int32{
	4, // 0: battle.v1.BattleSettledEvent.players:type_name -> battle.v1.PlayerResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_battle_v1_battle_proto_init() }
func file_api_battle_v1_battle_proto_init() {
	if File_api_battle_v1_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_battle_v1_battle_proto_rawDesc), len(file_api_battle_v1_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_battle_v1_battle_proto_goTypes,
		DependencyIndexes: file_api_battle_v1_battle_proto_depIdxs,
		MessageInfos:      file_api_battle_v1_battle_proto_msgTypes,
	}.Build()
	File_api_battle_v1_battle_proto = out.File
	file_api_battle_v1_battle_proto_goTypes = nil
	file_api_battle_v1_battle_proto_depIdxs = nil
}
