// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/battle/v1/battle_service.proto

package battlev1

import (
	_ "github.com/huangyuCN/atlas-sdk-go/api/atlas/v1"
	lockstep "github.com/huangyuCN/atlas-sdk-go/api/lockstep"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinBattleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleReq) Reset() {
	*x = JoinBattleReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleReq) ProtoMessage() {}

func (x *JoinBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleReq.ProtoReflect.Descriptor instead.
func (*JoinBattleReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{0}
}

func (x *JoinBattleReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type JoinBattleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *lockstep.SessionMeta  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CurrentFrame  uint64                 `protobuf:"varint,2,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
	Snapshot      *lockstep.SnapshotMeta `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleReply) Reset() {
	*x = JoinBattleReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleReply) ProtoMessage() {}

func (x *JoinBattleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleReply.ProtoReflect.Descriptor instead.
func (*JoinBattleReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinBattleReply) GetMeta() *lockstep.SessionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *JoinBattleReply) GetCurrentFrame() uint64 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

func (x *JoinBattleReply) GetSnapshot() *lockstep.SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type FrameInputReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BattleId      string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Input         *lockstep.LockstepInput `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputReq) Reset() {
	*x = FrameInputReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputReq) ProtoMessage() {}

func (x *FrameInputReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputReq.ProtoReflect.Descriptor instead.
func (*FrameInputReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{2}
}

func (x *FrameInputReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *FrameInputReq) GetInput() *lockstep.LockstepInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type FrameInputReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputReply) Reset() {
	*x = FrameInputReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputReply) ProtoMessage() {}

func (x *FrameInputReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputReply.ProtoReflect.Descriptor instead.
func (*FrameInputReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{3}
}

type SyncFramesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	LastSeenFrame uint64                 `protobuf:"varint,2,opt,name=last_seen_frame,json=lastSeenFrame,proto3" json:"last_seen_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFramesReq) Reset() {
	*x = SyncFramesReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFramesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFramesReq) ProtoMessage() {}

func (x *SyncFramesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFramesReq.ProtoReflect.Descriptor instead.
func (*SyncFramesReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{4}
}

func (x *SyncFramesReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *SyncFramesReq) GetLastSeenFrame() uint64 {
	if x != nil {
		return x.LastSeenFrame
	}
	return 0
}

type SyncFramesReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CurrentFrame  uint64                  `protobuf:"varint,1,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
	Snapshot      *lockstep.SnapshotMeta  `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Missed        []*lockstep.FrameInputs `protobuf:"bytes,3,rep,name=missed,proto3" json:"missed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFramesReply) Reset() {
	*x = SyncFramesReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFramesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFramesReply) ProtoMessage() {}

func (x *SyncFramesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFramesReply.ProtoReflect.Descriptor instead.
func (*SyncFramesReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{5}
}

func (x *SyncFramesReply) GetCurrentFrame() uint64 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

func (x *SyncFramesReply) GetSnapshot() *lockstep.SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SyncFramesReply) GetMissed() []*lockstep.FrameInputs {
	if x != nil {
		return x.Missed
	}
	return nil
}

type FrameBroadcast struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BattleId      string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Frame         *lockstep.LockstepFrame `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameBroadcast) Reset() {
	*x = FrameBroadcast{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameBroadcast) ProtoMessage() {}

func (x *FrameBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameBroadcast.ProtoReflect.Descriptor instead.
func (*FrameBroadcast) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{6}
}

func (x *FrameBroadcast) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *FrameBroadcast) GetFrame() *lockstep.LockstepFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type BattleEndNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BattleId       string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	WinnerPlayerId string                 `protobuf:"bytes,2,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BattleEndNotify) Reset() {
	*x = BattleEndNotify{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEndNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEndNotify) ProtoMessage() {}

func (x *BattleEndNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEndNotify.ProtoReflect.Descriptor instead.
func (*BattleEndNotify) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{7}
}

func (x *BattleEndNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleEndNotify) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

var File_api_battle_v1_battle_service_proto protoreflect.FileDescriptor

const file_api_battle_v1_battle_service_proto_rawDesc = "" +
	"\n" +
	"\"api/battle/v1/battle_service.proto\x12\tbattle.v1\x1a\x18api/atlas/v1/route.proto\x1a\x1aapi/battle/v1/battle.proto\x1a\x1bapi/lockstep/lockstep.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\rJoinBattleReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"\xab\x01\n" +
	"\x0fJoinBattleReply\x124\n" +
	"\x04meta\x18\x01 \x01(\v2 .atlas.game.lockstep.SessionMetaR\x04meta\x12#\n" +
	"\rcurrent_frame\x18\x02 \x01(\x04R\fcurrentFrame\x12=\n" +
	"\bsnapshot\x18\x03 \x01(\v2!.atlas.game.lockstep.SnapshotMetaR\bsnapshot\"f\n" +
	"\rFrameInputReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x128\n" +
	"\x05input\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepInputR\x05input\"\x11\n" +
	"\x0fFrameInputReply\"T\n" +
	"\rSyncFramesReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12&\n" +
	"\x0flast_seen_frame\x18\x02 \x01(\x04R\rlastSeenFrame\"\xaf\x01\n" +
	"\x0fSyncFramesReply\x12#\n" +
	"\rcurrent_frame\x18\x01 \x01(\x04R\fcurrentFrame\x12=\n" +
	"\bsnapshot\x18\x02 \x01(\v2!.atlas.game.lockstep.SnapshotMetaR\bsnapshot\x128\n" +
	"\x06missed\x18\x03 \x03(\v2 .atlas.game.lockstep.FrameInputsR\x06missed\"m\n" +
	"\x0eFrameBroadcast\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x128\n" +
	"\x05frame\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepFrameR\x05frame:\x04\xd8\xd5\"\x01\"^\n" +
	"\x0fBattleEndNotify\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12(\n" +
	"\x10winner_player_id\x18\x02 \x01(\tR\x0ewinnerPlayerId:\x04\xd8\xd5\"\x012\x8e\x03\n" +
	"\rBattleService\x12B\n" +
	"\n" +
	"JoinBattle\x12\x18.battle.v1.JoinBattleReq\x1a\x1a.battle.v1.JoinBattleReply\x12B\n" +
	"\x0eSendFrameInput\x12\x18.battle.v1.FrameInputReq\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\n" +
	"SyncFrames\x12\x18.battle.v1.SyncFramesReq\x1a\x1a.battle.v1.SyncFramesReply\x12N\n" +
	"\x06Create\x12\x1e.battle.v1.CreateBattleRequest\x1a\x1c.battle.v1.CreateBattleReply\"\x06\xd2\xd5\"\x02\b\x02\x12D\n" +
	"\bGetState\x12\x16.battle.v1.GetStateReq\x1a\x18.battle.v1.GetStateReply\"\x06\xd2\xd5\"\x02\b\x02\x1a\x1b\xca\xd5\"\x17\n" +
	"\x06battle\x10\x01\x18\x02\"\tbattle_idB?Z=github.com/huangyuCN/atlas-game-layout/api/battle/v1;battlev1b\x06proto3"

var (
	file_api_battle_v1_battle_service_proto_rawDescOnce sync.Once
	file_api_battle_v1_battle_service_proto_rawDescData []byte
)

func file_api_battle_v1_battle_service_proto_rawDescGZIP() []byte {
	file_api_battle_v1_battle_service_proto_rawDescOnce.Do(func() {
		file_api_battle_v1_battle_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_battle_v1_battle_service_proto_rawDesc), len(file_api_battle_v1_battle_service_proto_rawDesc)))
	})
	return file_api_battle_v1_battle_service_proto_rawDescData
}

var file_api_battle_v1_battle_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_battle_v1_battle_service_proto_goTypes = []any{
	(*JoinBattleReq)(nil),          // 0: battle.v1.JoinBattleReq
	(*JoinBattleReply)(nil),        // 1: battle.v1.JoinBattleReply
	(*FrameInputReq)(nil),          // 2: battle.v1.FrameInputReq
	(*FrameInputReply)(nil),        // 3: battle.v1.FrameInputReply
	(*SyncFramesReq)(nil),          // 4: battle.v1.SyncFramesReq
	(*SyncFramesReply)(nil),        // 5: battle.v1.SyncFramesReply
	(*FrameBroadcast)(nil),         // 6: battle.v1.FrameBroadcast
	(*BattleEndNotify)(nil),        // 7: battle.v1.BattleEndNotify
	(*lockstep.SessionMeta)(nil),   // 8: atlas.game.lockstep.SessionMeta
	(*lockstep.SnapshotMeta)(nil),  // 9: atlas.game.lockstep.SnapshotMeta
	(*lockstep.LockstepInput)(nil), // 10: atlas.game.lockstep.LockstepInput
	(*lockstep.FrameInputs)(nil),   // 11: atlas.game.lockstep.FrameInputs
	(*lockstep.LockstepFrame)(nil), // 12: atlas.game.lockstep.LockstepFrame
	(*CreateBattleRequest)(nil),    // 13: battle.v1.CreateBattleRequest
	(*GetStateReq)(nil),            // 14: battle.v1.GetStateReq
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
	(*CreateBattleReply)(nil),      // 16: battle.v1.CreateBattleReply
	(*GetStateReply)(nil),          // 17: battle.v1.GetStateReply
}
var file_api_battle_v1_battle_service_proto_depIdxs = []int32{
	8,  // 0: battle.v1.JoinBattleReply.meta:type_name -> atlas.game.lockstep.SessionMeta
	9,  // 1: battle.v1.JoinBattleReply.snapshot:type_name -> atlas.game.lockstep.SnapshotMeta
	10, // 2: battle.v1.FrameInputReq.input:type_name -> atlas.game.lockstep.LockstepInput
	9,  // 3: battle.v1.SyncFramesReply.snapshot:type_name -> atlas.game.lockstep.SnapshotMeta
	11, // 4: battle.v1.SyncFramesReply.missed:type_name -> atlas.game.lockstep.FrameInputs
	12, // 5: battle.v1.FrameBroadcast.frame:type_name -> atlas.game.lockstep.LockstepFrame
	0,  // 6: battle.v1.BattleService.JoinBattle:input_type -> battle.v1.JoinBattleReq
	2,  // 7: battle.v1.BattleService.SendFrameInput:input_type -> battle.v1.FrameInputReq
	4,  // 8: battle.v1.BattleService.SyncFrames:input_type -> battle.v1.SyncFramesReq
	13, // 9: battle.v1.BattleService.Create:input_type -> battle.v1.CreateBattleRequest
	14, // 10: battle.v1.BattleService.GetState:input_type -> battle.v1.GetStateReq
	1,  // 11: battle.v1.BattleService.JoinBattle:output_type -> battle.v1.JoinBattleReply
	15, // 12: battle.v1.BattleService.SendFrameInput:output_type -> google.protobuf.Empty
	5,  // 13: battle.v1.BattleService.SyncFrames:output_type -> battle.v1.SyncFramesReply
	16, // 14: battle.v1.BattleService.Create:output_type -> battle.v1.CreateBattleReply
	17, // 15: battle.v1.BattleService.GetState:output_type -> battle.v1.GetStateReply
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_battle_v1_battle_service_proto_init() }
func file_api_battle_v1_battle_service_proto_init() {
	if File_api_battle_v1_battle_service_proto != nil {
		return
	}
	file_api_battle_v1_battle_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_battle_v1_battle_service_proto_rawDesc), len(file_api_battle_v1_battle_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_battle_v1_battle_service_proto_goTypes,
		DependencyIndexes: file_api_battle_v1_battle_service_proto_depIdxs,
		MessageInfos:      file_api_battle_v1_battle_service_proto_msgTypes,
	}.Build()
	File_api_battle_v1_battle_service_proto = out.File
	file_api_battle_v1_battle_service_proto_goTypes = nil
	file_api_battle_v1_battle_service_proto_depIdxs = nil
}
