// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/battle/v1/battle_service.proto

package battlev1

import (
	_ "github.com/huangyuCN/atlas-sdk-go/api/atlas/v1"
	lockstep "github.com/huangyuCN/atlas-sdk-go/api/lockstep"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeTransport int32

const (
	EdgeTransport_EDGE_TRANSPORT_UNSPECIFIED EdgeTransport = 0
	EdgeTransport_EDGE_TRANSPORT_WS          EdgeTransport = 1
	EdgeTransport_EDGE_TRANSPORT_KCP         EdgeTransport = 2
	EdgeTransport_EDGE_TRANSPORT_UDP         EdgeTransport = 3
)

// Enum value maps for EdgeTransport.
var (
	EdgeTransport_name = map[int32]string{
		0: "EDGE_TRANSPORT_UNSPECIFIED",
		1: "EDGE_TRANSPORT_WS",
		2: "EDGE_TRANSPORT_KCP",
		3: "EDGE_TRANSPORT_UDP",
	}
	EdgeTransport_value = map[string]int32{
		"EDGE_TRANSPORT_UNSPECIFIED": 0,
		"EDGE_TRANSPORT_WS":          1,
		"EDGE_TRANSPORT_KCP":         2,
		"EDGE_TRANSPORT_UDP":         3,
	}
)

func (x EdgeTransport) Enum() *EdgeTransport {
	p := new(EdgeTransport)
	*p = x
	return p
}

func (x EdgeTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_api_battle_v1_battle_service_proto_enumTypes[0].Descriptor()
}

func (EdgeTransport) Type() protoreflect.EnumType {
	return &file_api_battle_v1_battle_service_proto_enumTypes[0]
}

func (x EdgeTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeTransport.Descriptor instead.
func (EdgeTransport) EnumDescriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{0}
}

type PlayerOutReason int32

const (
	PlayerOutReason_PLAYER_OUT_REASON_UNSPECIFIED     PlayerOutReason = 0
	PlayerOutReason_PLAYER_OUT_REASON_OFFLINE_TIMEOUT PlayerOutReason = 1
)

// Enum value maps for PlayerOutReason.
var (
	PlayerOutReason_name = map[int32]string{
		0: "PLAYER_OUT_REASON_UNSPECIFIED",
		1: "PLAYER_OUT_REASON_OFFLINE_TIMEOUT",
	}
	PlayerOutReason_value = map[string]int32{
		"PLAYER_OUT_REASON_UNSPECIFIED":     0,
		"PLAYER_OUT_REASON_OFFLINE_TIMEOUT": 1,
	}
)

func (x PlayerOutReason) Enum() *PlayerOutReason {
	p := new(PlayerOutReason)
	*p = x
	return p
}

func (x PlayerOutReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerOutReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_battle_v1_battle_service_proto_enumTypes[1].Descriptor()
}

func (PlayerOutReason) Type() protoreflect.EnumType {
	return &file_api_battle_v1_battle_service_proto_enumTypes[1]
}

func (x PlayerOutReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerOutReason.Descriptor instead.
func (PlayerOutReason) EnumDescriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{1}
}

type JoinBattleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleReq) Reset() {
	*x = JoinBattleReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleReq) ProtoMessage() {}

func (x *JoinBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleReq.ProtoReflect.Descriptor instead.
func (*JoinBattleReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{0}
}

func (x *JoinBattleReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type JoinBattleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *lockstep.SessionMeta  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CurrentFrame  uint64                 `protobuf:"varint,2,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
	Snapshot      *lockstep.SnapshotMeta `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleReply) Reset() {
	*x = JoinBattleReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleReply) ProtoMessage() {}

func (x *JoinBattleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleReply.ProtoReflect.Descriptor instead.
func (*JoinBattleReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinBattleReply) GetMeta() *lockstep.SessionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *JoinBattleReply) GetCurrentFrame() uint64 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

func (x *JoinBattleReply) GetSnapshot() *lockstep.SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type FrameInputReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BattleId      string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Input         *lockstep.LockstepInput `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputReq) Reset() {
	*x = FrameInputReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputReq) ProtoMessage() {}

func (x *FrameInputReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputReq.ProtoReflect.Descriptor instead.
func (*FrameInputReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{2}
}

func (x *FrameInputReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *FrameInputReq) GetInput() *lockstep.LockstepInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type FrameInputReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputReply) Reset() {
	*x = FrameInputReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputReply) ProtoMessage() {}

func (x *FrameInputReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputReply.ProtoReflect.Descriptor instead.
func (*FrameInputReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{3}
}

type SyncFramesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	LastSeenFrame uint64                 `protobuf:"varint,2,opt,name=last_seen_frame,json=lastSeenFrame,proto3" json:"last_seen_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFramesReq) Reset() {
	*x = SyncFramesReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFramesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFramesReq) ProtoMessage() {}

func (x *SyncFramesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFramesReq.ProtoReflect.Descriptor instead.
func (*SyncFramesReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{4}
}

func (x *SyncFramesReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *SyncFramesReq) GetLastSeenFrame() uint64 {
	if x != nil {
		return x.LastSeenFrame
	}
	return 0
}

type SyncFramesReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CurrentFrame  uint64                  `protobuf:"varint,1,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
	Snapshot      *lockstep.SnapshotMeta  `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Missed        []*lockstep.FrameInputs `protobuf:"bytes,3,rep,name=missed,proto3" json:"missed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFramesReply) Reset() {
	*x = SyncFramesReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFramesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFramesReply) ProtoMessage() {}

func (x *SyncFramesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFramesReply.ProtoReflect.Descriptor instead.
func (*SyncFramesReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{5}
}

func (x *SyncFramesReply) GetCurrentFrame() uint64 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

func (x *SyncFramesReply) GetSnapshot() *lockstep.SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SyncFramesReply) GetMissed() []*lockstep.FrameInputs {
	if x != nil {
		return x.Missed
	}
	return nil
}

type IssueEntryTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueEntryTicketReq) Reset() {
	*x = IssueEntryTicketReq{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueEntryTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueEntryTicketReq) ProtoMessage() {}

func (x *IssueEntryTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueEntryTicketReq.ProtoReflect.Descriptor instead.
func (*IssueEntryTicketReq) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{6}
}

func (x *IssueEntryTicketReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type EdgeEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     EdgeTransport          `protobuf:"varint,1,opt,name=transport,proto3,enum=battle.v1.EdgeTransport" json:"transport,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeEndpoint) Reset() {
	*x = EdgeEndpoint{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeEndpoint) ProtoMessage() {}

func (x *EdgeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeEndpoint.ProtoReflect.Descriptor instead.
func (*EdgeEndpoint) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{7}
}

func (x *EdgeEndpoint) GetTransport() EdgeTransport {
	if x != nil {
		return x.Transport
	}
	return EdgeTransport_EDGE_TRANSPORT_UNSPECIFIED
}

func (x *EdgeEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BattleTicketEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Ticket        []byte                 `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleTicketEntry) Reset() {
	*x = BattleTicketEntry{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleTicketEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleTicketEntry) ProtoMessage() {}

func (x *BattleTicketEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleTicketEntry.ProtoReflect.Descriptor instead.
func (*BattleTicketEntry) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{8}
}

func (x *BattleTicketEntry) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BattleTicketEntry) GetTicket() []byte {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type IssueEntryTicketReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoints       []*EdgeEndpoint        `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Tickets         []*BattleTicketEntry   `protobuf:"bytes,2,rep,name=tickets,proto3" json:"tickets,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,3,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueEntryTicketReply) Reset() {
	*x = IssueEntryTicketReply{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueEntryTicketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueEntryTicketReply) ProtoMessage() {}

func (x *IssueEntryTicketReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueEntryTicketReply.ProtoReflect.Descriptor instead.
func (*IssueEntryTicketReply) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{9}
}

func (x *IssueEntryTicketReply) GetEndpoints() []*EdgeEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *IssueEntryTicketReply) GetTickets() []*BattleTicketEntry {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *IssueEntryTicketReply) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type FrameBroadcast struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BattleId      string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Frame         *lockstep.LockstepFrame `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameBroadcast) Reset() {
	*x = FrameBroadcast{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameBroadcast) ProtoMessage() {}

func (x *FrameBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameBroadcast.ProtoReflect.Descriptor instead.
func (*FrameBroadcast) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{10}
}

func (x *FrameBroadcast) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *FrameBroadcast) GetFrame() *lockstep.LockstepFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type BattleEndNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BattleId       string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	WinnerPlayerId string                 `protobuf:"bytes,2,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BattleEndNotify) Reset() {
	*x = BattleEndNotify{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEndNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEndNotify) ProtoMessage() {}

func (x *BattleEndNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEndNotify.ProtoReflect.Descriptor instead.
func (*BattleEndNotify) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{11}
}

func (x *BattleEndNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleEndNotify) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

type PlayerOutNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        PlayerOutReason        `protobuf:"varint,3,opt,name=reason,proto3,enum=battle.v1.PlayerOutReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOutNotify) Reset() {
	*x = PlayerOutNotify{}
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOutNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOutNotify) ProtoMessage() {}

func (x *PlayerOutNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_battle_v1_battle_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOutNotify.ProtoReflect.Descriptor instead.
func (*PlayerOutNotify) Descriptor() ([]byte, []int) {
	return file_api_battle_v1_battle_service_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerOutNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *PlayerOutNotify) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOutNotify) GetReason() PlayerOutReason {
	if x != nil {
		return x.Reason
	}
	return PlayerOutReason_PLAYER_OUT_REASON_UNSPECIFIED
}

var File_api_battle_v1_battle_service_proto protoreflect.FileDescriptor

const file_api_battle_v1_battle_service_proto_rawDesc = "" +
	"\n" +
	"\"api/battle/v1/battle_service.proto\x12\tbattle.v1\x1a\x18api/atlas/v1/route.proto\x1a\x1aapi/battle/v1/battle.proto\x1a\x1bapi/lockstep/lockstep.proto\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\rJoinBattleReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"\xab\x01\n" +
	"\x0fJoinBattleReply\x124\n" +
	"\x04meta\x18\x01 \x01(\v2 .atlas.game.lockstep.SessionMetaR\x04meta\x12#\n" +
	"\rcurrent_frame\x18\x02 \x01(\x04R\fcurrentFrame\x12=\n" +
	"\bsnapshot\x18\x03 \x01(\v2!.atlas.game.lockstep.SnapshotMetaR\bsnapshot\"f\n" +
	"\rFrameInputReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x128\n" +
	"\x05input\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepInputR\x05input\"\x11\n" +
	"\x0fFrameInputReply\"T\n" +
	"\rSyncFramesReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12&\n" +
	"\x0flast_seen_frame\x18\x02 \x01(\x04R\rlastSeenFrame\"\xaf\x01\n" +
	"\x0fSyncFramesReply\x12#\n" +
	"\rcurrent_frame\x18\x01 \x01(\x04R\fcurrentFrame\x12=\n" +
	"\bsnapshot\x18\x02 \x01(\v2!.atlas.game.lockstep.SnapshotMetaR\bsnapshot\x128\n" +
	"\x06missed\x18\x03 \x03(\v2 .atlas.game.lockstep.FrameInputsR\x06missed\"2\n" +
	"\x13IssueEntryTicketReq\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\"`\n" +
	"\fEdgeEndpoint\x126\n" +
	"\ttransport\x18\x01 \x01(\x0e2\x18.battle.v1.EdgeTransportR\ttransport\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"H\n" +
	"\x11BattleTicketEntry\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06ticket\x18\x02 \x01(\fR\x06ticket\"\xb3\x01\n" +
	"\x15IssueEntryTicketReply\x125\n" +
	"\tendpoints\x18\x01 \x03(\v2\x17.battle.v1.EdgeEndpointR\tendpoints\x126\n" +
	"\atickets\x18\x02 \x03(\v2\x1c.battle.v1.BattleTicketEntryR\atickets\x12+\n" +
	"\x12expires_at_unix_ms\x18\x03 \x01(\x03R\x0fexpiresAtUnixMs\"m\n" +
	"\x0eFrameBroadcast\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x128\n" +
	"\x05frame\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepFrameR\x05frame:\x04\xd8\xd5\"\x01\"^\n" +
	"\x0fBattleEndNotify\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12(\n" +
	"\x10winner_player_id\x18\x02 \x01(\tR\x0ewinnerPlayerId:\x04\xd8\xd5\"\x01\"\x85\x01\n" +
	"\x0fPlayerOutNotify\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x122\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x1a.battle.v1.PlayerOutReasonR\x06reason:\x04\xd8\xd5\"\x01*v\n" +
	"\rEdgeTransport\x12\x1e\n" +
	"\x1aEDGE_TRANSPORT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EDGE_TRANSPORT_WS\x10\x01\x12\x16\n" +
	"\x12EDGE_TRANSPORT_KCP\x10\x02\x12\x16\n" +
	"\x12EDGE_TRANSPORT_UDP\x10\x03*[\n" +
	"\x0fPlayerOutReason\x12!\n" +
	"\x1dPLAYER_OUT_REASON_UNSPECIFIED\x10\x00\x12%\n" +
	"!PLAYER_OUT_REASON_OFFLINE_TIMEOUT\x10\x012\xec\x03\n" +
	"\rBattleService\x12B\n" +
	"\n" +
	"JoinBattle\x12\x18.battle.v1.JoinBattleReq\x1a\x1a.battle.v1.JoinBattleReply\x12B\n" +
	"\x0eSendFrameInput\x12\x18.battle.v1.FrameInputReq\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\n" +
	"SyncFrames\x12\x18.battle.v1.SyncFramesReq\x1a\x1a.battle.v1.SyncFramesReply\x12N\n" +
	"\x06Create\x12\x1e.battle.v1.CreateBattleRequest\x1a\x1c.battle.v1.CreateBattleReply\"\x06\xd2\xd5\"\x02\b\x02\x12D\n" +
	"\bGetState\x12\x16.battle.v1.GetStateReq\x1a\x18.battle.v1.GetStateReply\"\x06\xd2\xd5\"\x02\b\x02\x12\\\n" +
	"\x10IssueEntryTicket\x12\x1e.battle.v1.IssueEntryTicketReq\x1a .battle.v1.IssueEntryTicketReply\"\x06\xd2\xd5\"\x02\b\x02\x1a\x1b\xca\xd5\"\x17\n" +
	"\x06battle\x10\x01\x18\x02\"\tbattle_idB?Z=github.com/huangyuCN/atlas-game-layout/api/battle/v1;battlev1b\x06proto3"

var (
	file_api_battle_v1_battle_service_proto_rawDescOnce sync.Once
	file_api_battle_v1_battle_service_proto_rawDescData []byte
)

func file_api_battle_v1_battle_service_proto_rawDescGZIP() []byte {
	file_api_battle_v1_battle_service_proto_rawDescOnce.Do(func() {
		file_api_battle_v1_battle_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_battle_v1_battle_service_proto_rawDesc), len(file_api_battle_v1_battle_service_proto_rawDesc)))
	})
	return file_api_battle_v1_battle_service_proto_rawDescData
}

var file_api_battle_v1_battle_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_battle_v1_battle_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_battle_v1_battle_service_proto_goTypes = []any{
	(EdgeTransport)(0),             // 0: battle.v1.EdgeTransport
	(PlayerOutReason)(0),           // 1: battle.v1.PlayerOutReason
	(*JoinBattleReq)(nil),          // 2: battle.v1.JoinBattleReq
	(*JoinBattleReply)(nil),        // 3: battle.v1.JoinBattleReply
	(*FrameInputReq)(nil),          // 4: battle.v1.FrameInputReq
	(*FrameInputReply)(nil),        // 5: battle.v1.FrameInputReply
	(*SyncFramesReq)(nil),          // 6: battle.v1.SyncFramesReq
	(*SyncFramesReply)(nil),        // 7: battle.v1.SyncFramesReply
	(*IssueEntryTicketReq)(nil),    // 8: battle.v1.IssueEntryTicketReq
	(*EdgeEndpoint)(nil),           // 9: battle.v1.EdgeEndpoint
	(*BattleTicketEntry)(nil),      // 10: battle.v1.BattleTicketEntry
	(*IssueEntryTicketReply)(nil),  // 11: battle.v1.IssueEntryTicketReply
	(*FrameBroadcast)(nil),         // 12: battle.v1.FrameBroadcast
	(*BattleEndNotify)(nil),        // 13: battle.v1.BattleEndNotify
	(*PlayerOutNotify)(nil),        // 14: battle.v1.PlayerOutNotify
	(*lockstep.SessionMeta)(nil),   // 15: atlas.game.lockstep.SessionMeta
	(*lockstep.SnapshotMeta)(nil),  // 16: atlas.game.lockstep.SnapshotMeta
	(*lockstep.LockstepInput)(nil), // 17: atlas.game.lockstep.LockstepInput
	(*lockstep.FrameInputs)(nil),   // 18: atlas.game.lockstep.FrameInputs
	(*lockstep.LockstepFrame)(nil), // 19: atlas.game.lockstep.LockstepFrame
	(*CreateBattleRequest)(nil),    // 20: battle.v1.CreateBattleRequest
	(*GetStateReq)(nil),            // 21: battle.v1.GetStateReq
	(*emptypb.Empty)(nil),          // 22: google.protobuf.Empty
	(*CreateBattleReply)(nil),      // 23: battle.v1.CreateBattleReply
	(*GetStateReply)(nil),          // 24: battle.v1.GetStateReply
}
var file_api_battle_v1_battle_service_proto_depIdxs = []int32{
	15, // 0: battle.v1.JoinBattleReply.meta:type_name -> atlas.game.lockstep.SessionMeta
	16, // 1: battle.v1.JoinBattleReply.snapshot:type_name -> atlas.game.lockstep.SnapshotMeta
	17, // 2: battle.v1.FrameInputReq.input:type_name -> atlas.game.lockstep.LockstepInput
	16, // 3: battle.v1.SyncFramesReply.snapshot:type_name -> atlas.game.lockstep.SnapshotMeta
	18, // 4: battle.v1.SyncFramesReply.missed:type_name -> atlas.game.lockstep.FrameInputs
	0,  // 5: battle.v1.EdgeEndpoint.transport:type_name -> battle.v1.EdgeTransport
	9,  // 6: battle.v1.IssueEntryTicketReply.endpoints:type_name -> battle.v1.EdgeEndpoint
	10, // 7: battle.v1.IssueEntryTicketReply.tickets:type_name -> battle.v1.BattleTicketEntry
	19, // 8: battle.v1.FrameBroadcast.frame:type_name -> atlas.game.lockstep.LockstepFrame
	1,  // 9: battle.v1.PlayerOutNotify.reason:type_name -> battle.v1.PlayerOutReason
	2,  // 10: battle.v1.BattleService.JoinBattle:input_type -> battle.v1.JoinBattleReq
	4,  // 11: battle.v1.BattleService.SendFrameInput:input_type -> battle.v1.FrameInputReq
	6,  // 12: battle.v1.BattleService.SyncFrames:input_type -> battle.v1.SyncFramesReq
	20, // 13: battle.v1.BattleService.Create:input_type -> battle.v1.CreateBattleRequest
	21, // 14: battle.v1.BattleService.GetState:input_type -> battle.v1.GetStateReq
	8,  // 15: battle.v1.BattleService.IssueEntryTicket:input_type -> battle.v1.IssueEntryTicketReq
	3,  // 16: battle.v1.BattleService.JoinBattle:output_type -> battle.v1.JoinBattleReply
	22, // 17: battle.v1.BattleService.SendFrameInput:output_type -> google.protobuf.Empty
	7,  // 18: battle.v1.BattleService.SyncFrames:output_type -> battle.v1.SyncFramesReply
	23, // 19: battle.v1.BattleService.Create:output_type -> battle.v1.CreateBattleReply
	24, // 20: battle.v1.BattleService.GetState:output_type -> battle.v1.GetStateReply
	11, // 21: battle.v1.BattleService.IssueEntryTicket:output_type -> battle.v1.IssueEntryTicketReply
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_battle_v1_battle_service_proto_init() }
func file_api_battle_v1_battle_service_proto_init() {
	if File_api_battle_v1_battle_service_proto != nil {
		return
	}
	file_api_battle_v1_battle_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_battle_v1_battle_service_proto_rawDesc), len(file_api_battle_v1_battle_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_battle_v1_battle_service_proto_goTypes,
		DependencyIndexes: file_api_battle_v1_battle_service_proto_depIdxs,
		EnumInfos:         file_api_battle_v1_battle_service_proto_enumTypes,
		MessageInfos:      file_api_battle_v1_battle_service_proto_msgTypes,
	}.Build()
	File_api_battle_v1_battle_service_proto = out.File
	file_api_battle_v1_battle_service_proto_goTypes = nil
	file_api_battle_v1_battle_service_proto_depIdxs = nil
}
