// Code generated by protoc-gen-atlas-client. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-client v0.1.0
// - protoc             v5.26.1
// source: api/gateway/v1/session.proto

package gatewayv1opclient

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-sdk-go/api/gateway/v1"
	client "github.com/huangyuCN/atlas-sdk-go/client"
)

// Session 是 Session 的业务 op 客户端 stub（atlas.route.v1 注解生成）：
// 方法直接映射客户端可达 rpc，经会话通道发送；身份由会话携带（消息体不含 token/player_id）。
// 与 gRPC 生成的 SessionClient（连接级 client）不是一回事。
type Session struct {
	cli client.Invoker
}

// NewSession 以会话内核构造 client stub。
func NewSession(cli client.Invoker) *Session {
	return &Session{cli: cli}
}

// Register 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *Session) Register(ctx context.Context, req *v1.RegisterRequest, opts ...client.InvokeOption) (*v1.RegisterReply, error) {
	var out v1.RegisterReply
	if err := c.cli.Invoke(ctx, `/gateway.v1.Session/Register`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Login 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *Session) Login(ctx context.Context, req *v1.LoginRequest, opts ...client.InvokeOption) (*v1.LoginReply, error) {
	var out v1.LoginReply
	if err := c.cli.Invoke(ctx, `/gateway.v1.Session/Login`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Resume 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *Session) Resume(ctx context.Context, req *v1.ResumeRequest, opts ...client.InvokeOption) (*v1.ResumeReply, error) {
	var out v1.ResumeReply
	if err := c.cli.Invoke(ctx, `/gateway.v1.Session/Resume`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *Session) Logout(ctx context.Context, req *v1.LogoutRequest, opts ...client.InvokeOption) (*v1.LogoutReply, error) {
	var out v1.LogoutReply
	if err := c.cli.Invoke(ctx, `/gateway.v1.Session/Logout`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Heartbeat 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *Session) Heartbeat(ctx context.Context, req *v1.HeartbeatRequest, opts ...client.InvokeOption) (*v1.HeartbeatReply, error) {
	var out v1.HeartbeatReply
	if err := c.cli.Invoke(ctx, `/gateway.v1.Session/Heartbeat`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// SessionProtocolOps 是 Session 的会话 op 名（按 rpc 名索引）。
var SessionProtocolOps = struct {
	Register  string
	Login     string
	Resume    string
	Logout    string
	Heartbeat string
}{
	Register:  "/gateway.v1.Session/Register",
	Login:     "/gateway.v1.Session/Login",
	Resume:    "/gateway.v1.Session/Resume",
	Logout:    "/gateway.v1.Session/Logout",
	Heartbeat: "/gateway.v1.Session/Heartbeat",
}

// SessionToken 从会话消息里取 Token（无该字段的消息返回零值）。
func SessionToken(msg any) string {
	switch m := msg.(type) {
	case *v1.LoginReply:
		return m.Token
	case *v1.ResumeRequest:
		return m.Token
	}
	return ""
}

// SessionPlayerID 从会话消息里取 PlayerID（无该字段的消息返回零值）。
func SessionPlayerID(msg any) string {
	switch m := msg.(type) {
	case *v1.RegisterReply:
		return m.PlayerId
	case *v1.LoginRequest:
		return m.PlayerId
	case *v1.LoginReply:
		return m.PlayerId
	case *v1.ResumeRequest:
		return m.PlayerId
	case *v1.ResumeReply:
		return m.PlayerId
	}
	return ""
}

// SessionExpiresAt 从会话消息里取 ExpiresAt（无该字段的消息返回零值）。
func SessionExpiresAt(msg any) int64 {
	return 0
}

// SessionPushOps 是 api/gateway/v1/session.proto 声明的服务端推送 op（客户端按 op 分发）。
var SessionPushOps = struct {
	KickedNotify string
}{
	KickedNotify: "/gateway.v1.KickedNotify",
}
