// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/lockstep/lockstep.proto

package locksteppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockstepMode int32

const (
	LockstepMode_LOCKSTEP_MODE_UNSPECIFIED          LockstepMode = 0
	LockstepMode_LOCKSTEP_MODE_SERVER_AUTHORITATIVE LockstepMode = 1
	LockstepMode_LOCKSTEP_MODE_P2P                  LockstepMode = 2
)

// Enum value maps for LockstepMode.
var (
	LockstepMode_name = map[int32]string{
		0: "LOCKSTEP_MODE_UNSPECIFIED",
		1: "LOCKSTEP_MODE_SERVER_AUTHORITATIVE",
		2: "LOCKSTEP_MODE_P2P",
	}
	LockstepMode_value = map[string]int32{
		"LOCKSTEP_MODE_UNSPECIFIED":          0,
		"LOCKSTEP_MODE_SERVER_AUTHORITATIVE": 1,
		"LOCKSTEP_MODE_P2P":                  2,
	}
)

func (x LockstepMode) Enum() *LockstepMode {
	p := new(LockstepMode)
	*p = x
	return p
}

func (x LockstepMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockstepMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_lockstep_lockstep_proto_enumTypes[0].Descriptor()
}

func (LockstepMode) Type() protoreflect.EnumType {
	return &file_api_lockstep_lockstep_proto_enumTypes[0]
}

func (x LockstepMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockstepMode.Descriptor instead.
func (LockstepMode) EnumDescriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{0}
}

type SessionMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MaxPlayers        uint32                 `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	MaxSpectators     uint32                 `protobuf:"varint,3,opt,name=max_spectators,json=maxSpectators,proto3" json:"max_spectators,omitempty"`
	TickMillis        uint32                 `protobuf:"varint,4,opt,name=tick_millis,json=tickMillis,proto3" json:"tick_millis,omitempty"`
	InputDelayFrames  uint32                 `protobuf:"varint,5,opt,name=input_delay_frames,json=inputDelayFrames,proto3" json:"input_delay_frames,omitempty"`
	MaxRollbackFrames uint32                 `protobuf:"varint,6,opt,name=max_rollback_frames,json=maxRollbackFrames,proto3" json:"max_rollback_frames,omitempty"`
	Mode              LockstepMode           `protobuf:"varint,7,opt,name=mode,proto3,enum=atlas.game.lockstep.LockstepMode" json:"mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionMeta) Reset() {
	*x = SessionMeta{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMeta) ProtoMessage() {}

func (x *SessionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMeta.ProtoReflect.Descriptor instead.
func (*SessionMeta) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{0}
}

func (x *SessionMeta) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMeta) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *SessionMeta) GetMaxSpectators() uint32 {
	if x != nil {
		return x.MaxSpectators
	}
	return 0
}

func (x *SessionMeta) GetTickMillis() uint32 {
	if x != nil {
		return x.TickMillis
	}
	return 0
}

func (x *SessionMeta) GetInputDelayFrames() uint32 {
	if x != nil {
		return x.InputDelayFrames
	}
	return 0
}

func (x *SessionMeta) GetMaxRollbackFrames() uint32 {
	if x != nil {
		return x.MaxRollbackFrames
	}
	return 0
}

func (x *SessionMeta) GetMode() LockstepMode {
	if x != nil {
		return x.Mode
	}
	return LockstepMode_LOCKSTEP_MODE_UNSPECIFIED
}

type LockstepInput struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FrameId                uint64                 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	PlayerId               string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Payload                []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Predicted              bool                   `protobuf:"varint,4,opt,name=predicted,proto3" json:"predicted,omitempty"`
	ClientSendTimeUnixNano int64                  `protobuf:"varint,5,opt,name=client_send_time_unix_nano,json=clientSendTimeUnixNano,proto3" json:"client_send_time_unix_nano,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LockstepInput) Reset() {
	*x = LockstepInput{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockstepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockstepInput) ProtoMessage() {}

func (x *LockstepInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockstepInput.ProtoReflect.Descriptor instead.
func (*LockstepInput) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{1}
}

func (x *LockstepInput) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *LockstepInput) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LockstepInput) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LockstepInput) GetPredicted() bool {
	if x != nil {
		return x.Predicted
	}
	return false
}

func (x *LockstepInput) GetClientSendTimeUnixNano() int64 {
	if x != nil {
		return x.ClientSendTimeUnixNano
	}
	return 0
}

type FrameInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameId       uint64                 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Inputs        []*LockstepInput       `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputs) Reset() {
	*x = FrameInputs{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputs) ProtoMessage() {}

func (x *FrameInputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputs.ProtoReflect.Descriptor instead.
func (*FrameInputs) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{2}
}

func (x *FrameInputs) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *FrameInputs) GetInputs() []*LockstepInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type SnapshotMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameId       uint64                 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	StateHash     []byte                 `protobuf:"bytes,2,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StorageKey    string                 `protobuf:"bytes,4,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMeta) Reset() {
	*x = SnapshotMeta{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMeta) ProtoMessage() {}

func (x *SnapshotMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMeta.ProtoReflect.Descriptor instead.
func (*SnapshotMeta) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotMeta) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *SnapshotMeta) GetStateHash() []byte {
	if x != nil {
		return x.StateHash
	}
	return nil
}

func (x *SnapshotMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SnapshotMeta) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

type LockstepFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameId       uint64                 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Inputs        []*LockstepInput       `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	StateHash     []byte                 `protobuf:"bytes,3,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Snapshot      *SnapshotMeta          `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockstepFrame) Reset() {
	*x = LockstepFrame{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockstepFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockstepFrame) ProtoMessage() {}

func (x *LockstepFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockstepFrame.ProtoReflect.Descriptor instead.
func (*LockstepFrame) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{4}
}

func (x *LockstepFrame) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *LockstepFrame) GetInputs() []*LockstepInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *LockstepFrame) GetStateHash() []byte {
	if x != nil {
		return x.StateHash
	}
	return nil
}

func (x *LockstepFrame) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *LockstepFrame) GetSnapshot() *SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SessionMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionRequest) GetMeta() *SessionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SessionMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionReply) Reset() {
	*x = CreateSessionReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionReply) ProtoMessage() {}

func (x *CreateSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionReply.ProtoReflect.Descriptor instead.
func (*CreateSessionReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionReply) GetMeta() *SessionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{7}
}

func (x *DestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DestroySessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionReply) Reset() {
	*x = DestroySessionReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionReply) ProtoMessage() {}

func (x *DestroySessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionReply.ProtoReflect.Descriptor instead.
func (*DestroySessionReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{8}
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{9}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinSessionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SessionMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	CurrentFrame  uint64                 `protobuf:"varint,2,opt,name=current_frame,json=currentFrame,proto3" json:"current_frame,omitempty"`
	Snapshot      *SnapshotMeta          `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionReply) Reset() {
	*x = JoinSessionReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionReply) ProtoMessage() {}

func (x *JoinSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionReply.ProtoReflect.Descriptor instead.
func (*JoinSessionReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{10}
}

func (x *JoinSessionReply) GetMeta() *SessionMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *JoinSessionReply) GetCurrentFrame() uint64 {
	if x != nil {
		return x.CurrentFrame
	}
	return 0
}

func (x *JoinSessionReply) GetSnapshot() *SnapshotMeta {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type LeaveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionRequest) Reset() {
	*x = LeaveSessionRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionRequest) ProtoMessage() {}

func (x *LeaveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionRequest.ProtoReflect.Descriptor instead.
func (*LeaveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LeaveSessionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LeaveSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionReply) Reset() {
	*x = LeaveSessionReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionReply) ProtoMessage() {}

func (x *LeaveSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionReply.ProtoReflect.Descriptor instead.
func (*LeaveSessionReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{12}
}

type PushInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         *LockstepInput         `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushInputRequest) Reset() {
	*x = PushInputRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInputRequest) ProtoMessage() {}

func (x *PushInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInputRequest.ProtoReflect.Descriptor instead.
func (*PushInputRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{13}
}

func (x *PushInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushInputRequest) GetInput() *LockstepInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type PushInputReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcceptedFrameId uint64                 `protobuf:"varint,1,opt,name=accepted_frame_id,json=acceptedFrameId,proto3" json:"accepted_frame_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushInputReply) Reset() {
	*x = PushInputReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushInputReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInputReply) ProtoMessage() {}

func (x *PushInputReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInputReply.ProtoReflect.Descriptor instead.
func (*PushInputReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{14}
}

func (x *PushInputReply) GetAcceptedFrameId() uint64 {
	if x != nil {
		return x.AcceptedFrameId
	}
	return 0
}

type SyncFrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromFrameId   uint64                 `protobuf:"varint,2,opt,name=from_frame_id,json=fromFrameId,proto3" json:"from_frame_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFrameRequest) Reset() {
	*x = SyncFrameRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFrameRequest) ProtoMessage() {}

func (x *SyncFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFrameRequest.ProtoReflect.Descriptor instead.
func (*SyncFrameRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{15}
}

func (x *SyncFrameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyncFrameRequest) GetFromFrameId() uint64 {
	if x != nil {
		return x.FromFrameId
	}
	return 0
}

func (x *SyncFrameRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncFrameReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Frames           []*LockstepFrame       `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	ConfirmedFrameId uint64                 `protobuf:"varint,2,opt,name=confirmed_frame_id,json=confirmedFrameId,proto3" json:"confirmed_frame_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncFrameReply) Reset() {
	*x = SyncFrameReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFrameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFrameReply) ProtoMessage() {}

func (x *SyncFrameReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFrameReply.ProtoReflect.Descriptor instead.
func (*SyncFrameReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{16}
}

func (x *SyncFrameReply) GetFrames() []*LockstepFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *SyncFrameReply) GetConfirmedFrameId() uint64 {
	if x != nil {
		return x.ConfirmedFrameId
	}
	return 0
}

type SpectateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromFrameId   uint64                 `protobuf:"varint,2,opt,name=from_frame_id,json=fromFrameId,proto3" json:"from_frame_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectateRequest) Reset() {
	*x = SpectateRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectateRequest) ProtoMessage() {}

func (x *SpectateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectateRequest.ProtoReflect.Descriptor instead.
func (*SpectateRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{17}
}

func (x *SpectateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SpectateRequest) GetFromFrameId() uint64 {
	if x != nil {
		return x.FromFrameId
	}
	return 0
}

type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromFrameId   uint64                 `protobuf:"varint,2,opt,name=from_frame_id,json=fromFrameId,proto3" json:"from_frame_id,omitempty"`
	ToFrameId     uint64                 `protobuf:"varint,3,opt,name=to_frame_id,json=toFrameId,proto3" json:"to_frame_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{18}
}

func (x *ReplayRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplayRequest) GetFromFrameId() uint64 {
	if x != nil {
		return x.FromFrameId
	}
	return 0
}

func (x *ReplayRequest) GetToFrameId() uint64 {
	if x != nil {
		return x.ToFrameId
	}
	return 0
}

type ReplayFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *LockstepFrame         `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayFrame) Reset() {
	*x = ReplayFrame{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayFrame) ProtoMessage() {}

func (x *ReplayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayFrame.ProtoReflect.Descriptor instead.
func (*ReplayFrame) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{19}
}

func (x *ReplayFrame) GetFrame() *LockstepFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type ScanInputsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId         string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FromFrameId      uint64                 `protobuf:"varint,3,opt,name=from_frame_id,json=fromFrameId,proto3" json:"from_frame_id,omitempty"`
	ToFrameId        uint64                 `protobuf:"varint,4,opt,name=to_frame_id,json=toFrameId,proto3" json:"to_frame_id,omitempty"`
	FromTimeUnixNano int64                  `protobuf:"varint,5,opt,name=from_time_unix_nano,json=fromTimeUnixNano,proto3" json:"from_time_unix_nano,omitempty"`
	ToTimeUnixNano   int64                  `protobuf:"varint,6,opt,name=to_time_unix_nano,json=toTimeUnixNano,proto3" json:"to_time_unix_nano,omitempty"`
	MaxRecords       uint32                 `protobuf:"varint,7,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScanInputsRequest) Reset() {
	*x = ScanInputsRequest{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanInputsRequest) ProtoMessage() {}

func (x *ScanInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanInputsRequest.ProtoReflect.Descriptor instead.
func (*ScanInputsRequest) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{20}
}

func (x *ScanInputsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScanInputsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ScanInputsRequest) GetFromFrameId() uint64 {
	if x != nil {
		return x.FromFrameId
	}
	return 0
}

func (x *ScanInputsRequest) GetToFrameId() uint64 {
	if x != nil {
		return x.ToFrameId
	}
	return 0
}

func (x *ScanInputsRequest) GetFromTimeUnixNano() int64 {
	if x != nil {
		return x.FromTimeUnixNano
	}
	return 0
}

func (x *ScanInputsRequest) GetToTimeUnixNano() int64 {
	if x != nil {
		return x.ToTimeUnixNano
	}
	return 0
}

func (x *ScanInputsRequest) GetMaxRecords() uint32 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

type InputRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         *LockstepInput         `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRecord) Reset() {
	*x = InputRecord{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRecord) ProtoMessage() {}

func (x *InputRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRecord.ProtoReflect.Descriptor instead.
func (*InputRecord) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{21}
}

func (x *InputRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InputRecord) GetInput() *LockstepInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type ScanInputsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*InputRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanInputsReply) Reset() {
	*x = ScanInputsReply{}
	mi := &file_api_lockstep_lockstep_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanInputsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanInputsReply) ProtoMessage() {}

func (x *ScanInputsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_lockstep_lockstep_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanInputsReply.ProtoReflect.Descriptor instead.
func (*ScanInputsReply) Descriptor() ([]byte, []int) {
	return file_api_lockstep_lockstep_proto_rawDescGZIP(), []int{22}
}

func (x *ScanInputsReply) GetRecords() []*InputRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_api_lockstep_lockstep_proto protoreflect.FileDescriptor

const file_api_lockstep_lockstep_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/lockstep/lockstep.proto\x12\x13atlas.game.lockstep\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x02\n" +
	"\vSessionMeta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\rR\n" +
	"maxPlayers\x12%\n" +
	"\x0emax_spectators\x18\x03 \x01(\rR\rmaxSpectators\x12\x1f\n" +
	"\vtick_millis\x18\x04 \x01(\rR\n" +
	"tickMillis\x12,\n" +
	"\x12input_delay_frames\x18\x05 \x01(\rR\x10inputDelayFrames\x12.\n" +
	"\x13max_rollback_frames\x18\x06 \x01(\rR\x11maxRollbackFrames\x125\n" +
	"\x04mode\x18\a \x01(\x0e2!.atlas.game.lockstep.LockstepModeR\x04mode\"\xbb\x01\n" +
	"\rLockstepInput\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x04R\aframeId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tpredicted\x18\x04 \x01(\bR\tpredicted\x12:\n" +
	"\x1aclient_send_time_unix_nano\x18\x05 \x01(\x03R\x16clientSendTimeUnixNano\"d\n" +
	"\vFrameInputs\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x04R\aframeId\x12:\n" +
	"\x06inputs\x18\x02 \x03(\v2\".atlas.game.lockstep.LockstepInputR\x06inputs\"\x88\x01\n" +
	"\fSnapshotMeta\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x04R\aframeId\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x02 \x01(\fR\tstateHash\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1f\n" +
	"\vstorage_key\x18\x04 \x01(\tR\n" +
	"storageKey\"\x81\x02\n" +
	"\rLockstepFrame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x04R\aframeId\x12:\n" +
	"\x06inputs\x18\x02 \x03(\v2\".atlas.game.lockstep.LockstepInputR\x06inputs\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x03 \x01(\fR\tstateHash\x12;\n" +
	"\vserver_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12=\n" +
	"\bsnapshot\x18\x05 \x01(\v2!.atlas.game.lockstep.SnapshotMetaR\bsnapshot\"L\n" +
	"\x14CreateSessionRequest\x124\n" +
	"\x04meta\x18\x01 \x01(\v2 .atlas.game.lockstep.SessionMetaR\x04meta\"J\n" +
	"\x12CreateSessionReply\x124\n" +
	"\x04meta\x18\x01 \x01(\v2 .atlas.game.lockstep.SessionMetaR\x04meta\"6\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x15\n" +
	"\x13DestroySessionReply\"P\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\xac\x01\n" +
	"\x10JoinSessionReply\x124\n" +
	"\x04meta\x18\x01 \x01(\v2 .atlas.game.lockstep.SessionMetaR\x04meta\x12#\n" +
	"\rcurrent_frame\x18\x02 \x01(\x04R\fcurrentFrame\x12=\n" +
	"\bsnapshot\x18\x03 \x01(\v2!.atlas.game.lockstep.SnapshotMetaR\bsnapshot\"Q\n" +
	"\x13LeaveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x13\n" +
	"\x11LeaveSessionReply\"k\n" +
	"\x10PushInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\x05input\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepInputR\x05input\"<\n" +
	"\x0ePushInputReply\x12*\n" +
	"\x11accepted_frame_id\x18\x01 \x01(\x04R\x0facceptedFrameId\"k\n" +
	"\x10SyncFrameRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\rfrom_frame_id\x18\x02 \x01(\x04R\vfromFrameId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"z\n" +
	"\x0eSyncFrameReply\x12:\n" +
	"\x06frames\x18\x01 \x03(\v2\".atlas.game.lockstep.LockstepFrameR\x06frames\x12,\n" +
	"\x12confirmed_frame_id\x18\x02 \x01(\x04R\x10confirmedFrameId\"T\n" +
	"\x0fSpectateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\rfrom_frame_id\x18\x02 \x01(\x04R\vfromFrameId\"r\n" +
	"\rReplayRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\rfrom_frame_id\x18\x02 \x01(\x04R\vfromFrameId\x12\x1e\n" +
	"\vto_frame_id\x18\x03 \x01(\x04R\ttoFrameId\"G\n" +
	"\vReplayFrame\x128\n" +
	"\x05frame\x18\x01 \x01(\v2\".atlas.game.lockstep.LockstepFrameR\x05frame\"\x8e\x02\n" +
	"\x11ScanInputsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\"\n" +
	"\rfrom_frame_id\x18\x03 \x01(\x04R\vfromFrameId\x12\x1e\n" +
	"\vto_frame_id\x18\x04 \x01(\x04R\ttoFrameId\x12-\n" +
	"\x13from_time_unix_nano\x18\x05 \x01(\x03R\x10fromTimeUnixNano\x12)\n" +
	"\x11to_time_unix_nano\x18\x06 \x01(\x03R\x0etoTimeUnixNano\x12\x1f\n" +
	"\vmax_records\x18\a \x01(\rR\n" +
	"maxRecords\"f\n" +
	"\vInputRecord\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\x05input\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepInputR\x05input\"M\n" +
	"\x0fScanInputsReply\x12:\n" +
	"\arecords\x18\x01 \x03(\v2 .atlas.game.lockstep.InputRecordR\arecords*l\n" +
	"\fLockstepMode\x12\x1d\n" +
	"\x19LOCKSTEP_MODE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"LOCKSTEP_MODE_SERVER_AUTHORITATIVE\x10\x01\x12\x15\n" +
	"\x11LOCKSTEP_MODE_P2P\x10\x022\xd0\x06\n" +
	"\bLockstep\x12c\n" +
	"\rCreateSession\x12).atlas.game.lockstep.CreateSessionRequest\x1a'.atlas.game.lockstep.CreateSessionReply\x12f\n" +
	"\x0eDestroySession\x12*.atlas.game.lockstep.DestroySessionRequest\x1a(.atlas.game.lockstep.DestroySessionReply\x12]\n" +
	"\vJoinSession\x12'.atlas.game.lockstep.JoinSessionRequest\x1a%.atlas.game.lockstep.JoinSessionReply\x12`\n" +
	"\fLeaveSession\x12(.atlas.game.lockstep.LeaveSessionRequest\x1a&.atlas.game.lockstep.LeaveSessionReply\x12W\n" +
	"\tPushInput\x12%.atlas.game.lockstep.PushInputRequest\x1a#.atlas.game.lockstep.PushInputReply\x12W\n" +
	"\tSyncFrame\x12%.atlas.game.lockstep.SyncFrameRequest\x1a#.atlas.game.lockstep.SyncFrameReply\x12V\n" +
	"\bSpectate\x12$.atlas.game.lockstep.SpectateRequest\x1a\".atlas.game.lockstep.LockstepFrame0\x01\x12P\n" +
	"\x06Replay\x12\".atlas.game.lockstep.ReplayRequest\x1a .atlas.game.lockstep.ReplayFrame0\x01\x12Z\n" +
	"\n" +
	"ScanInputs\x12&.atlas.game.lockstep.ScanInputsRequest\x1a$.atlas.game.lockstep.ScanInputsReplyB4Z2github.com/huangyuCN/atlas/api/lockstep;locksteppbb\x06proto3"

var (
	file_api_lockstep_lockstep_proto_rawDescOnce sync.Once
	file_api_lockstep_lockstep_proto_rawDescData []byte
)

func file_api_lockstep_lockstep_proto_rawDescGZIP() []byte {
	file_api_lockstep_lockstep_proto_rawDescOnce.Do(func() {
		file_api_lockstep_lockstep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lockstep_lockstep_proto_rawDesc), len(file_api_lockstep_lockstep_proto_rawDesc)))
	})
	return file_api_lockstep_lockstep_proto_rawDescData
}

var file_api_lockstep_lockstep_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_lockstep_lockstep_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_lockstep_lockstep_proto_goTypes = []any{
	(LockstepMode)(0),             // 0: atlas.game.lockstep.LockstepMode
	(*SessionMeta)(nil),           // 1: atlas.game.lockstep.SessionMeta
	(*LockstepInput)(nil),         // 2: atlas.game.lockstep.LockstepInput
	(*FrameInputs)(nil),           // 3: atlas.game.lockstep.FrameInputs
	(*SnapshotMeta)(nil),          // 4: atlas.game.lockstep.SnapshotMeta
	(*LockstepFrame)(nil),         // 5: atlas.game.lockstep.LockstepFrame
	(*CreateSessionRequest)(nil),  // 6: atlas.game.lockstep.CreateSessionRequest
	(*CreateSessionReply)(nil),    // 7: atlas.game.lockstep.CreateSessionReply
	(*DestroySessionRequest)(nil), // 8: atlas.game.lockstep.DestroySessionRequest
	(*DestroySessionReply)(nil),   // 9: atlas.game.lockstep.DestroySessionReply
	(*JoinSessionRequest)(nil),    // 10: atlas.game.lockstep.JoinSessionRequest
	(*JoinSessionReply)(nil),      // 11: atlas.game.lockstep.JoinSessionReply
	(*LeaveSessionRequest)(nil),   // 12: atlas.game.lockstep.LeaveSessionRequest
	(*LeaveSessionReply)(nil),     // 13: atlas.game.lockstep.LeaveSessionReply
	(*PushInputRequest)(nil),      // 14: atlas.game.lockstep.PushInputRequest
	(*PushInputReply)(nil),        // 15: atlas.game.lockstep.PushInputReply
	(*SyncFrameRequest)(nil),      // 16: atlas.game.lockstep.SyncFrameRequest
	(*SyncFrameReply)(nil),        // 17: atlas.game.lockstep.SyncFrameReply
	(*SpectateRequest)(nil),       // 18: atlas.game.lockstep.SpectateRequest
	(*ReplayRequest)(nil),         // 19: atlas.game.lockstep.ReplayRequest
	(*ReplayFrame)(nil),           // 20: atlas.game.lockstep.ReplayFrame
	(*ScanInputsRequest)(nil),     // 21: atlas.game.lockstep.ScanInputsRequest
	(*InputRecord)(nil),           // 22: atlas.game.lockstep.InputRecord
	(*ScanInputsReply)(nil),       // 23: atlas.game.lockstep.ScanInputsReply
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_api_lockstep_lockstep_proto_depIdxs = []int32{
	0,  // 0: atlas.game.lockstep.SessionMeta.mode:type_name -> atlas.game.lockstep.LockstepMode
	2,  // 1: atlas.game.lockstep.FrameInputs.inputs:type_name -> atlas.game.lockstep.LockstepInput
	2,  // 2: atlas.game.lockstep.LockstepFrame.inputs:type_name -> atlas.game.lockstep.LockstepInput
	24, // 3: atlas.game.lockstep.LockstepFrame.server_time:type_name -> google.protobuf.Timestamp
	4,  // 4: atlas.game.lockstep.LockstepFrame.snapshot:type_name -> atlas.game.lockstep.SnapshotMeta
	1,  // 5: atlas.game.lockstep.CreateSessionRequest.meta:type_name -> atlas.game.lockstep.SessionMeta
	1,  // 6: atlas.game.lockstep.CreateSessionReply.meta:type_name -> atlas.game.lockstep.SessionMeta
	1,  // 7: atlas.game.lockstep.JoinSessionReply.meta:type_name -> atlas.game.lockstep.SessionMeta
	4,  // 8: atlas.game.lockstep.JoinSessionReply.snapshot:type_name -> atlas.game.lockstep.SnapshotMeta
	2,  // 9: atlas.game.lockstep.PushInputRequest.input:type_name -> atlas.game.lockstep.LockstepInput
	5,  // 10: atlas.game.lockstep.SyncFrameReply.frames:type_name -> atlas.game.lockstep.LockstepFrame
	5,  // 11: atlas.game.lockstep.ReplayFrame.frame:type_name -> atlas.game.lockstep.LockstepFrame
	2,  // 12: atlas.game.lockstep.InputRecord.input:type_name -> atlas.game.lockstep.LockstepInput
	22, // 13: atlas.game.lockstep.ScanInputsReply.records:type_name -> atlas.game.lockstep.InputRecord
	6,  // 14: atlas.game.lockstep.Lockstep.CreateSession:input_type -> atlas.game.lockstep.CreateSessionRequest
	8,  // 15: atlas.game.lockstep.Lockstep.DestroySession:input_type -> atlas.game.lockstep.DestroySessionRequest
	10, // 16: atlas.game.lockstep.Lockstep.JoinSession:input_type -> atlas.game.lockstep.JoinSessionRequest
	12, // 17: atlas.game.lockstep.Lockstep.LeaveSession:input_type -> atlas.game.lockstep.LeaveSessionRequest
	14, // 18: atlas.game.lockstep.Lockstep.PushInput:input_type -> atlas.game.lockstep.PushInputRequest
	16, // 19: atlas.game.lockstep.Lockstep.SyncFrame:input_type -> atlas.game.lockstep.SyncFrameRequest
	18, // 20: atlas.game.lockstep.Lockstep.Spectate:input_type -> atlas.game.lockstep.SpectateRequest
	19, // 21: atlas.game.lockstep.Lockstep.Replay:input_type -> atlas.game.lockstep.ReplayRequest
	21, // 22: atlas.game.lockstep.Lockstep.ScanInputs:input_type -> atlas.game.lockstep.ScanInputsRequest
	7,  // 23: atlas.game.lockstep.Lockstep.CreateSession:output_type -> atlas.game.lockstep.CreateSessionReply
	9,  // 24: atlas.game.lockstep.Lockstep.DestroySession:output_type -> atlas.game.lockstep.DestroySessionReply
	11, // 25: atlas.game.lockstep.Lockstep.JoinSession:output_type -> atlas.game.lockstep.JoinSessionReply
	13, // 26: atlas.game.lockstep.Lockstep.LeaveSession:output_type -> atlas.game.lockstep.LeaveSessionReply
	15, // 27: atlas.game.lockstep.Lockstep.PushInput:output_type -> atlas.game.lockstep.PushInputReply
	17, // 28: atlas.game.lockstep.Lockstep.SyncFrame:output_type -> atlas.game.lockstep.SyncFrameReply
	5,  // 29: atlas.game.lockstep.Lockstep.Spectate:output_type -> atlas.game.lockstep.LockstepFrame
	20, // 30: atlas.game.lockstep.Lockstep.Replay:output_type -> atlas.game.lockstep.ReplayFrame
	23, // 31: atlas.game.lockstep.Lockstep.ScanInputs:output_type -> atlas.game.lockstep.ScanInputsReply
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_lockstep_lockstep_proto_init() }
func file_api_lockstep_lockstep_proto_init() {
	if File_api_lockstep_lockstep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lockstep_lockstep_proto_rawDesc), len(file_api_lockstep_lockstep_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lockstep_lockstep_proto_goTypes,
		DependencyIndexes: file_api_lockstep_lockstep_proto_depIdxs,
		EnumInfos:         file_api_lockstep_lockstep_proto_enumTypes,
		MessageInfos:      file_api_lockstep_lockstep_proto_msgTypes,
	}.Build()
	File_api_lockstep_lockstep_proto = out.File
	file_api_lockstep_lockstep_proto_goTypes = nil
	file_api_lockstep_lockstep_proto_depIdxs = nil
}
